### ISSUE TITLE
inconsistency between osrm results and mapbox geocode api

### ISSUE THREAD

**Issue by carocad** [mapbox/mapbox-gl-geocoder#111]
Hey guys,

I couldnt find any other place to report this issue so I hope here is ok. I am building a mobile app and as I was doing some tests with mapbox geocoding API I realized that there were some "places missing". After doing some digging I found out that for some reason the place that I was looking for was not returned by the mapbox geocoding API even though the information is clearly in OSM.

To give a proper example:
- searching `frankfurt, westbahnhof` on the geocoder returns nothing useful since there seems to be no match.
- searching for `frankfurt, westbahnhof` on the OSRM demo does return the proper location of it

I think this might be a bug since AFAIK both mapbox and OSRM use OSM data to do the lookup.

I hope it helps and sorry for posting it here but I couldnt find the geocoding engine repo on github :(

**Comment by KaiBot3000** [comment]
Hey @carocad, thanks for the report!
Our geocoder runs a mix of open data and proprietary data, so we won't always have the same features as OSM. If you notice anything missing, please feel free to submit a report using our geocoder-feedback tool at https://www.mapbox.com/geocoder-feedback/ . We're adding new data to our geocoder all the time, and we appreciate knowing where we could improve. I'm closing this for now, and thanks again!
