### ISSUE TITLE
Cannot specify container

### ISSUE THREAD

**Issue by jvence** [mapbox/mapbox-gl-geocoder#113]
Previous versions allowed is to specify a container to place the geocoder input box. 'container' option is currently ignored in latest version. I can see from changelog: `container` option removed - attaching the control outside of the map is no longer supported - not sure why this was done this way.

**Comment by andrewharvey** [comment]
@jvence see https://github.com/mapbox/mapbox-gl-geocoder/issues/92#issuecomment-274829454

**Comment by mollymerp** [comment]
Thanks @andrewharvey -
@jvence :
> a direct option to specify a container was dropped in favour of aligning better with https://github.com/mapbox/mapbox-gl-js which doesn't have a built-in mechanism for specifying elements outside the map container.

> But it's still possible! addTo returns the control container so you can append it to any arbitrary DOM node. Here's an example of that: http://bl.ocks.org/tristen/a09627f01d3a3bc54139d52a5eb01386
