### ISSUE TITLE
Be able to pass array to types and country?

### ISSUE THREAD

**Issue by lukasmartinelli** [mapbox/mapbox-gl-geocoder#114]
It expected the API to be able to deal with an array of strings instead of a comma separated string.
A little convenience 😉

**Comment by mollymerp** [comment]
this is an upstream issues in https://github.com/mapbox/mapbox-sdk-js/ closing here as I've ticketed in that repo.

**Comment by andrewharvey** [comment]
- [ ] do new mapbox-sdk-js release
- [ ] update package.json with new mapbox-sdk-js relase

after that this should be possible

**Comment by andrewharvey** [comment]
- [ ] do new mapbox-sdk-js release
- [ ] update package.json with new mapbox-sdk-js relase

after that this should be possible
