### ISSUE TITLE
make clear method public

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#115]
The `_clear` method is private, this can be useful for applications extending the geocoder. Is there any reason not to make it public? I'm happy to make the change and add the documentation in a PR but wanted to understand if there was any reasoning behind it.

**Comment by scottsfarley93** [comment]
Hey @andrewharvey curious if you've had any recent thoughts on this issue. If not, I can take a stab at doing this and get it into our version 4.0.0 release, but wanted to check first to see if you wanted to PR this change.

**Comment by andrewharvey** [comment]
I still think it's a good idea to make this method public. I haven't done any work on this, so all yours if you wanted to PR it.
