### ISSUE TITLE
Proximity updates based on map movement

### ISSUE THREAD

**Issue by keyofj** [mapbox/mapbox-gl-geocoder#118]
When the MapboxGeocoder is initialized we can set the proximity based on the current map center point. It would be nice to be able to have this updated based on where the user has the map when they do subsequent searches.  Not automatic though, I think it should be set as needed to not interfere with specific user experiences.

In our case if someone returns to a saved map they were working on in Dallas, the initial proximity works well if they want to search around Texas. If they jump over to California to work in the map, search results would be returned relative to that current area.

**Comment by andrewharvey** [comment]
what about a `geocoder.setProximity(proximity)` method which would then allow this to be implemented in the application code with:

```
map.on('moveend', function() {
   geocoder.setProximity(map.getCenter());
})
```

**Comment by tristen** [comment]
> what about a `geocoder.setProximity(proximity)` method 

That sounds like a good addition to add.

**Comment by andrewharvey** [comment]
I've merged #122 which now let's you implement this with:

```js
map.on('load', updateGeocoderProximity);
map.on('moveend', updateGeocoderProximity);

function updateGeocoderProximity() {
    if (map.getZoom() > 9) { // proximity is designed for local scale, if the user is looking at the whole world, it doesn't make sense to factor in the arbitrary centre of the map
        var center = map.getCenter().wrap();
        geocoder.setProximity({ longitude: center.lng, latitude: center.lat });
    } else {
        geocoder.setProximity(null);
    }
}

```

I'm leaving this issue open to track automatically doing this by passing a `trackProximity: true` option.

**Comment by siddmegadeth** [comment]
but how to update geocoder search box on mapmove event

**Comment by andrewharvey** [comment]
> but how to update geocoder search box on mapmove event

@siddmegadeth could you elaborate?
