### ISSUE TITLE
allow spaces in comma separated types option

### ISSUE THREAD

**Issue by keyofj** [mapbox/mapbox-gl-geocoder#120]
mapboxgl - 0.37.0
geocoder - 2.1.0

The request documentation states that you can pass multiple types separated by a comma into the options: [API.md](https://www.mapbox.com/api-documentation/#request-format) but the following error is thrown if more than one is passed in.

`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at r.<anonymous> (mapbox-gl-geocoder.min.js:1)
    at <anonymous>`

I have found that this is caused if a space is present between the types:

`var m = new MapboxGeocoder({
        types: "district, place"
})`

It would be great when parsing the types if each value was trimmed and/or the documentation updated to show the proper formatting.

Thanks.

**Comment by andrewharvey** [comment]
I'm :+1: for adding options like `types` to the main example at https://github.com/mapbox/mapbox-gl-geocoder/blob/master/lib/index.js#L34

**Comment by andrewharvey** [comment]
See also https://github.com/mapbox/mapbox-gl-geocoder/issues/114 which is closely related.

**Comment by mollymerp** [comment]
I think this and #114 are upstream issues in https://github.com/mapbox/mapbox-sdk-js/

**Comment by mollymerp** [comment]
👍  to adding an example with correct `types` formatting in the meantime though

**Comment by andrewharvey** [comment]
- [ ] do new mapbox-sdk-js release
- [ ] update package.json with new mapbox-sdk-js relase

after that this should be possible
