### ISSUE TITLE
'language' parameter doesn't have effect

### ISSUE THREAD

**Issue by tompec** [mapbox/mapbox-gl-geocoder#129]
Hi there 👋,

The `language` parameter doesn't work.

**What I've tried:**
```js
map.addControl(new MapboxGeocoder({
    accessToken: mapboxgl.accessToken,
    language: 'fr'
}));
```
Query: 'lisbon'.

**What it does:**
The results stay unchanged.
The ajax request looks like that:
`https://api.mapbox.com/geocoding/v5/mapbox.places/lisbon.json?limit=5&access_token=ACCESS_TOKEN`

instead of that
`https://api.mapbox.com/geocoding/v5/mapbox.places/lisbon.json?language=fr&limit=5&access_token=ACCESS_TOKEN`

Thanks for your help!

**Comment by andrewharvey** [comment]
Are you using mapbox-gl-geocoder 2.1.1? This feature was only added in that version as per the [CHANGELOG](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/CHANGELOG.md)

I can confirm with a minimal example that it works.

https://jsbin.com/dupuhukavo/edit?html,output

The request is then `https://api.mapbox.com/geocoding/v5/mapbox.places/test.json?access_token=ACCESS_TOKEN&limit=5&language=fr`

Can you provide a minimal example of where you're seeing it not working?
