### ISSUE TITLE
Add center and width css option(s) -- feature request

### ISSUE THREAD

**Issue by majesticpdx** [mapbox/mapbox-gl-geocoder#13]
Hello, 

I already started a feature request on the GL JS side and was referred over here. I'm hoping that it would be possible to add both a center and width css property to the geocoder plugin. 

A good example of this can be found here: https://www.mapbox.com/bites/00121/

This would word better for longer strings and is easier for the end user as well.

I did notice that the css appears to be on the GL JS style sheet vs the geocoder style sheet. 

Thanks again.

**Comment by tristen** [comment]
Hi @majesticpdx

There's no plans to add a center option to the geocoder control but it's easy enough to get this desired effect by specifying a `container` in the geocoder options and using a dash of CSS. Here's an example: http://bl.ocks.org/tristen/290112a562f205d141c0

**Comment by majesticpdx** [comment]
Thank you @tristen, your help is appreciated.
