### ISSUE TITLE
add example to use any element as the geocoder input

### ISSUE THREAD

**Issue by astrojams1** [mapbox/mapbox-gl-geocoder#137]
I have a mapbox map with a legend below. I would like to use a contenteditable div within the legend as my geocoder input rather than have the input box live within the mapbox map container.

**Comment by andrewharvey** [comment]
Is https://github.com/mapbox/mapbox-gl-geocoder/issues/92#issuecomment-274829454 what you wanted to do? This has come up a few times so we should include better documentation on how to do this.

**Comment by astrojams1** [comment]
Thank you - I think so, but the example attached to that comment doesn't appear to work (this one: https://bl.ocks.org/tristen/a09627f01d3a3bc54139d52a5eb01386). 

One thing that example doesn't cover: I happen to be building all this in React, and so I have the additional challenge of wanting to have my map and input in separate components with a common parent component <App />. I suppose I need to define the map and geocoder in <App /> and then pass these as props to the components housing the map and input?

**Comment by andrewharvey** [comment]
The access token is no longer valid, could you update it with your own locally to verify that the solution is still valid?

Sorry I don't know React so can't comment on that.

**Comment by astrojams1** [comment]
It is indeed still valid when I change the accessToken - thank you.

**Comment by andrewharvey** [comment]
Good to hear, I've re-purposed this ticket to track the documentation improvements so this is more obvious.

**Comment by andrewharvey** [comment]
done in #139
