### ISSUE TITLE
Brazilian postal codes are incomplete

### ISSUE THREAD

**Issue by matnarcizo** [mapbox/mapbox-gl-geocoder#141]
Hi,

I'm testing the Mapbox Geocode API to get informations about Brazillian addresses, and I realized that the postal codes are incomplete, and sometimes wrong.

Postal codes in Brazil are composed by eight numbers, but the Mapbox API are returning only the first five.

I've tried to change the language to Portuguese, but the problem persists.

Here's the result search for an address in the Brazil Post Office Service (CEP is our postal code):
![image](https://user-images.githubusercontent.com/18445524/34531073-3e891c36-f098-11e7-8e97-05fecede16d5.png)

And the result in the Mapzen API Playground:
![image](https://user-images.githubusercontent.com/18445524/34531176-a1b1dec4-f098-11e7-82e8-f2a8989f71af.png)

It's a know issue? If so, there's a solution? 

Thanks :)

**Comment by andrewharvey** [comment]
Hi @matnarcizo this repository is for the Geocoder Control for Mapbox GL JS (it's mostly just the user interface search box), for issues regarding the Mapbox Geocoding API you'll need to [contact Mapbox Support](https://www.mapbox.com/contact/support/).

I'm closing this issue as it's an API issue and nothing can be done on the UI Control level.

**Comment by felipebelluco** [comment]
@matnarcizo did you find a solution for that issue?
