### ISSUE TITLE
Geocoder not returning all results?

### ISSUE THREAD

**Issue by astrojams1** [mapbox/mapbox-gl-geocoder#147]
I have a problem where my geocoder does not return places that I am pretty certain do exist in the mapbox database. Case in point: I found an online mapbox map that clearly shows "Rainbow Grocery Coop"
![screen shot 2018-02-28 at 6 32 15 pm](https://user-images.githubusercontent.com/1023503/36824373-c38c7c9e-1cb6-11e8-9f97-3d40729a0dfa.png)

However, when I search for this place, It does not come up (notice, for example, that Rainbow Grocery is located in Colorado, whereas the Rainbow Grocery I am interested in is in San Francisco).

![screen shot 2018-02-28 at 6 36 02 pm](https://user-images.githubusercontent.com/1023503/36824384-dd4fa48a-1cb6-11e8-8364-1cca756568fa.png)

This example comes from my personal project irlmap.com

The code snippet that returns the search results is:

```
geocodeThis(query) {
    const { homePoint } = this.state
    const accessToken = this.state.settings.accessToken
    // axios.get('/geocoding/v5/mapbox.places/'+encodeURIComponent(query)+'.json?access_token='+accessToken+'&proximity='+homePoint.geometry.coordinates[0]+','+homePoint.geometry.coordinates[1])
    // axios.get('/geocoding/v5/mapbox.places/'+encodeURI(query)+'.json?access_token='+accessToken+'&proximity='+homePoint.geometry.coordinates[0]+','+homePoint.geometry.coordinates[1])
    axios.get('/geocoding/v5/mapbox.places/'+query+'.json?access_token='+accessToken+'&proximity='+homePoint.geometry.coordinates[0]+','+homePoint.geometry.coordinates[1])
      .then((response) => {
        this.setState({suggestions: response.data.features})
      })
      .catch((error) => {
        console.log(error);
      });
  }
```

**Comment by ingalls** [comment]
Thanks for the feedback and wonderful screenshots @astrojams1 

Unfortunately at this time are POIs layer is sourced from a 3rd party provider and not from OSM.
Outside of cities with active mapping communities, the OSM data isn't complete enough to use as a sole source. 

If you find missing data feel free to report it here: https://www.mapbox.com/geocoder-feedback/
