### ISSUE TITLE
default placeholder text should be localized if language option provided

### ISSUE THREAD

**Issue by vfoss** [mapbox/mapbox-gl-geocoder#150]
The placeholder text in the search bar for the geocoder remains "Search" (in English), even when the language of the map is changed, as in 
`let geocoder = new MapboxGeocoder({accessToken: mapboxgl.accessToken, language: 'es' });`.  I cannot figure out a clean way to change it.

**Comment by andrewharvey** [comment]
@vfoss You can set it with the [`placeholder` option](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#mapboxgeocoder).

But let's leave this ticked open to make the default placeholder set by the first language if provided.

**Comment by andrewharvey** [comment]
Done in https://github.com/mapbox/mapbox-gl-geocoder/tree/version4 by #201, slated for v4 release.
