### ISSUE TITLE
include matching text in suggestions

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#153]
Currently results will be displayed in whichever language was set in the options.

`{ language: 'en', country: 'au' }`

![en_au](https://user-images.githubusercontent.com/117278/40681595-eb112c12-63cc-11e8-8c5f-b23873bf905b.png)

`{ language: 'zh', country: 'au' }`

![zh_au](https://user-images.githubusercontent.com/117278/40681657-13fca322-63cd-11e8-9435-9fe656b176cf.png)

To get results displayed in one language, but still display the matching text if the query was in another language you need to do something like:

```
geocoder._typeahead.getItemValue = function (item) {
    if (item.matching_text) { // matching text is the text the query matched, so will be in the same language that the user queried in
        return item.matching_text + ' (' + item.place_name + ')';
    } else {
        return item.place_name;
    }
};
```

![zh_au_matching_text](https://user-images.githubusercontent.com/117278/40681878-aabb2252-63cd-11e8-813e-0ea2d32f1c02.png)

That feels a bit hacky though, I'm thinking if doing this be better supported without overwriting the internal `_typeahead.getItemValue` method, or even if this should become the default?

**Comment by scottsfarley93** [comment]
What about adding a constructor option to provide a function that allows implementation-specific customization over how the results are displayed? 

Something like:

```
var geocoder = new MapboxGeocoder({ 
    accessToken: mapboxgl.accessToken,
    render: function(result){
        return item.matching_text + ' (' + item.place_name + ')'
   }
})
```

We could provide a sensible default (either keep it the same as it is now (use `place_name`)  or use a function that renders the matching text in the dropdown), but provide the ability to override with something different if desired.

**Comment by andrewharvey** [comment]
:+1: I think that's the way to go.

Rethinking about this, the current defaults are probably good as they are.

**Comment by scottsfarley93** [comment]
The ability to do this was introduced in #208. While the defaults have not changed, once version 4 is released, additional fields can be accessed via the `render` function.
