### ISSUE TITLE
Minor styling suggestion when dropdown is open

### ISSUE THREAD

**Issue by jdaudier** [mapbox/mapbox-gl-geocoder#167]
When the dropdown is open for the geocoder, the `mapboxgl-ctrl-geocoder` div should have `0` bottom border radius. Minor styling suggestion.

## BEFORE
![](https://zappy.zapier.com/35C2FDB7-1FE1-4C0A-90BB-1529288D17DF.png)

## AFTER
![](https://zappy.zapier.com/FC68C066-0BF5-4104-81AD-5283DDB534E5.png)

**Comment by katydecorah** [comment]
Thank you for reporting! This fix was completed in #211 and will be live in version 4 #197
