### ISSUE TITLE
Reverse Geocoding 

### ISSUE THREAD

**Issue by CodeZeno** [mapbox/mapbox-gl-geocoder#168]
Reverse geocoding does not work unless the limit is set to 1.
I get a http status 422:
https://api.mapbox.com/geocoding/v5/mapbox.places/-122.1162864%2C37.4133183.json?access_token=xxx&limit=5

However if I set the limit to 1 it works but then my forward geocoding is also limited to 1 which is unwanted.

`var geocoder = new MapboxGeocoder({
accessToken: mapboxgl.accessToken,
limit:1
});
geocoder.query("-122.1162864,37.4133183");`

**Comment by andrewharvey** [comment]
I'm not sure this library was designed for that, you could either use https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#reversegeocode or create two different MapboxGeocoders, one not added to the map and using the limit 1 for your reverse geocodes.

**Comment by CodeZeno** [comment]
@andrewharvey The library does say it's "a geocoder control for mapbox-gl-js using the Mapbox Geocoding API" and Mapbox Geocoding API has those options.
I tried creating a second geocoder that is not added to the map but it fails due to some styling not being able to be applied.
I have a work around for now where I change the limit option and replace it with itself which seems to work but probably not the best way.

```
geocoder.options.limit = 5;
document.getElementById('geocoder').replaceChild(geocoder.onAdd($scope.map), document.getElementById('geocoder').childNodes[0]);
```

**Comment by CodeZeno** [comment]
The use case is we use a service that gives us the lng,lat based on the users IP address, we then convert that to the text representation of the closest result.
We then show markers for each of our locations that are closest to that result.
We basically use this as a good default as it is usually accurate enough to show them our locations that are close to them without any annoying popups.
If it happens to show the location of an ISP that is further away from the user they can still search or click the geolocation button and allow the browser to disclose that info.

I'll look into mapbox-sdk-js.

**Comment by andrewharvey** [comment]
I think it's better to use mapbox-sdk-js for that, as it's designed for reverse geocodes. MapboxGeocoder is only really designed for user driven autocompleting forward geocodes.
