### ISSUE TITLE
local geocoder not displaying typed result

### ISSUE THREAD

**Issue by rcowling** [mapbox/mapbox-gl-geocoder#169]
Hello,

I am using the mapbox localgeocoder to work with my goejson data. I am using it with zip codes. Whenever I type in a zipcode from my geojson data for example: "97230" it is not the first result on the list, sometimes it is the 5th or 6th result, sometimes it is not on the list at all. Is there a way to correct this? 

Using the method here: `https://www.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/

``

**Comment by rcowling** [comment]
> [mapbox-gl-geocoder/lib/index.js](https://github.com/mapbox/mapbox-gl-geocoder/blob/c6a1450c57533ffc6fdeb05eed26b5432ac02383/lib/index.js#L190)
> 
> Line 190 in [c6a1450](/mapbox/mapbox-gl-geocoder/commit/c6a1450c57533ffc6fdeb05eed26b5432ac02383)
> 
>  res.features = res.features ? localGeocoderRes.concat(res.features) : localGeocoderRes; 
> The `localGeocoder` results should appear at the top do you have a minimal example you can share of the issue?

@andrewharvey here is a working example: https://rcowling.github.io/oregon/

Lets say if you want to use zipcode '97230' which I know is in my dataset. If I type 972... it doesn't even come up at or when I type the full thing. Sometimes it comes up but is not the first result. Can you provide any insight? Thanks!

**Comment by rcowling** [comment]
I have tried this using a different dataset, I thought maybe it was my data but same result. The data is coming from a tileset in mapbox studio, perhaps that is why?

**Comment by andrewharvey** [comment]
@rcowling looking at your code there:


```
var geocoder = new MapboxGeocoder({
--
  | accessToken: mapboxgl.accessToken,
  | zoom: 8,
  | minLength: 5,
  | limit: 5,
  | bbox: [-124.5664, 41.9920, -116.4633, 46.2938], // replace this with the bbox of the state
  | types: 'postcode',
  | placeholder: "Enter a Zip Code."
  | });
```

You never pass it the `localGeocoder` option, so it won't be using any of your supplied data.

You need to pass that option, it won't automatically detect and use your own dataset/tileset data.

Take a look at the example https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/

**Comment by andrewharvey** [comment]
closing as I can't see anything to address on the mapbox-gl-geocoder side, please feel free to post back if that's wrong.
