### ISSUE TITLE
Latitude <-> longitude

### ISSUE THREAD

**Issue by Rabot18** [mapbox/mapbox-gl-geocoder#178]
Hello,

I'v just install this package on my project with npm but i have a problem when i search something, it works, but when i click on the result, it locates me at a wrong place. It switches latitude and longitude.

Example with Nantes in France : https://imgur.com/a/u7Qtlyq
And on the map i'm in Indian Ocean... 

Thanks in advance for your help.

**Comment by Rabot18** [comment]
Same problem with  "@mapbox/mapbox-gl-geocoder": "^2.3.0", :(

**Comment by andrewharvey** [comment]
That's really weird it works fine for me at https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/

**Comment by andrewharvey** [comment]
![screenshot from 2019-01-28 20-33-45](https://user-images.githubusercontent.com/117278/51826815-0c20d900-233c-11e9-891e-18ded2c55ac9.png)

Yeah, I can't replicate this. Do you have any more details about what you did to get the issue?

**Comment by Rabot18** [comment]
I think it's my bad. I test and I'm getting back to you
