### ISSUE TITLE
+1MB of JS - the unpleasant effect of anonymous event tracking

### ISSUE THREAD

**Issue by jimutt** [mapbox/mapbox-gl-geocoder#188]
Hi!
I recently discovered that the 3.1.2 release (https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v3.1.2/mapbox-gl-geocoder.min.js) has a size of over 1MB. Compared to the modestly sized 3.1.1 release at 36k: https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v3.1.1/mapbox-gl-geocoder.min.js

I believe it maybe was an unfortunate mistake to include dependencies (Without any investigation I guess the `request` and `crypto` packages are the main cause) inducing this huge increase in size.

**Comment by andrewharvey** [comment]
wow good catch @jimutt.

It does indeed appear to be due to dependencies introduced in #183, @scottsfarley93 hope you're able to take a look.

**Comment by scottsfarley93** [comment]
Interesting. I can take a look at this later this week.

**Comment by scottsfarley93** [comment]
After removing dependencies, the js bundle is now 75.148kb. It is available in v3.1.6.
