### ISSUE TITLE
Including intersecting streets

### ISSUE THREAD

**Issue by majesticpdx** [mapbox/mapbox-gl-geocoder#19]
Are there any plans to include intersecting streets with the gl-geocoder?

**Comment by apendleton** [comment]
Firstly, this library's geocoding support wraps Mapbox's [public geocoding API](https://www.mapbox.com/developers/api/geocoding/), just as our other libraries that include geocoding do, so it won't have special geocoding features that our other libraries don't.

As to intersecting streets, I assume you're referring to queries like "14th St. and T St., Washington, DC." Mapbox's geocoding API doesn't support this kind of query right now. It's something we'd like to support, but we have no specific timeline as to when it will be added. If and when we do add support to the API, this library should support it automatically, without needing to do anything special.
