### ISSUE TITLE
Improve default options set to improve search relevance

### ISSUE THREAD

**Issue by scottsfarley93** [mapbox/mapbox-gl-geocoder#195]
Looking at the options that are set on the geocoding call (https://github.com/mapbox/mapbox-gl-geocoder/blob/master/lib/index.js#L58), there are several defaults that could be configured to provide a better out-of-the box search experience. 

Specifically, I think good improvements could be found with:
- setting `trackProximity` to default true -- searches with a user-relevant proximity are likely to be more relevant
- setting a default language based on the user's browser settings

I suspect this may change user's expectations and/or be a breaking change -- so we could target this for the next major release.

**Comment by andrewharvey** [comment]
I think these are positive changes.

> I suspect this may change user's expectations and/or be a breaking change -- so we could target this for the next major release.

I agree.

**Comment by katydecorah** [comment]
👍 I also think that these are positive changes

**Comment by andrewharvey** [comment]
Done in https://github.com/mapbox/mapbox-gl-geocoder/tree/version4 by #200 #202, slated for v4 release.
