### ISSUE TITLE
Error During npm start

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [mapbox/mapbox-gl-geocoder#21]
Getting the following error with the 0.1.0 release when I try to `npm start` or require this into another app with `require('mapbox-gl-geocoder')`

ReferenceError: [BABEL] /Users/abe/Development/pcwaPoliticalBoundaries/node_modules/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.js: Unknown option: /Users/abe/Development/pcwaPoliticalBoundaries/node_modules/mapbox-gl-geocoder/dist/.babelrc.presets while parsing file: /Users/abe/Development/pcwaPoliticalBoundaries/node_modules/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.js

**Comment by drewbo** [comment]
@wheredoesyourmindgo this may be related to babel version mismatches. Can you try pulling the latest version from GitHub (rather than npm) and seeing if that resolves it?

**Comment by tmcw** [comment]
I think we should reel the complexity back, remove babel, switch to es5 https://github.com/mapbox/mapbox-gl-geocoder/issues/24 . This is a non-react, 210 line library: it doesn't need all the wheelies and tricks it is using.

**Comment by wheredoesyourmindgo** [comment]
npm install --save https://github.com/mapbox/mapbox-gl-geocoder.git  

Give me
