### ISSUE TITLE
minor css bug in 4.0.0beta

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-geocoder#238]
See here:

![Screen Shot 2019-04-05 at 5 52 55 PM](https://user-images.githubusercontent.com/108094/55662777-a9304000-57cb-11e9-956f-db50fecc2914.png)

Looks like this rule: https://github.com/mapbox/mapbox-gl-geocoder/blob/6f872246c518aabfb3b262eefdb3b156bccb4bdd/lib/mapbox-gl-geocoder.css#L190

takes precedence over this rule: https://github.com/mapbox/mapbox-gl-geocoder/blob/6f872246c518aabfb3b262eefdb3b156bccb4bdd/lib/mapbox-gl-geocoder.css#L64

Which means on larger screens, width isn't suing the  `.collapsed` value:
![Screen Shot 2019-04-05 at 5 55 24 PM](https://user-images.githubusercontent.com/108094/55662838-34113a80-57cc-11e9-9013-7c60f91b381c.png)

cc: @scottsfarley93 @katydecorah

**Comment by scottsfarley93** [comment]
Closed by #244

**Comment by katydecorah** [comment]
I merged #244 into the wrong branch and this didn't make it in v4 🤦‍♂️but I've rolled it into https://github.com/mapbox/mapbox-gl-geocoder/pull/249 with a few other CSS bug fixes
