### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-geocoder#24]
This code really doesn't need to use babel, and would benefit greatly from cutting unnecessary complexity.

**Comment by drewbo** [comment]
:+1:

**Comment by drewbo** [comment]
Having some problems with the build steps now, worth fixing or is anyone undertaking an ES5 rewrite?

**Comment by tristen** [comment]
@drewbo yep. started in: https://github.com/mapbox/mapbox-gl-geocoder/tree/un-es6

**Comment by drewbo** [comment]
:heart_eyes: Awesome, I luckily didn't get that far in only 8 minutes. Feel free to just include my small change from #26 in the rewrite instead of pulling that in separately (I can also reconfigure the PR after you merge yours)
