### ISSUE TITLE
geocoder x is not quite centered

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-geocoder#241]
looks like the x is a couple pixels too low:

![Screen Shot 2019-04-05 at 6 06 45 PM](https://user-images.githubusercontent.com/108094/55662957-9cace700-57cd-11e9-9499-0f48c9f511af.png)

I'm using the geocoder with `collapsed: true` if that makes a difference. Flex box centering would be the right tool for the job here.

**Comment by katydecorah** [comment]
@samanpwbb I'm not having luck recreating this, unfortunately. Do you have a reduced test case handy?

**Comment by katydecorah** [comment]
In Saman's example Assembly's `button` reset is causing the misalignment. Looks like we'll need to clear out the font and line-height on `.mapboxgl-ctrl-geocoder button` to prevent the icon position from being changed by other libraries/resets
