### ISSUE TITLE
Broken link in readme examples section

### ISSUE THREAD

**Issue by karenell** [mapbox/mapbox-gl-geocoder#247]
The last link in the [examples section of the readme](https://github.com/mapbox/mapbox-gl-geocoder#examples) ("Bias geocoder results around the map view") isn't working. 

@scottsfarley93 tagging you here to update or remove the link.

**Comment by andrewharvey** [comment]
Yes this example became redundant by the trackProximity option and the fact that it became on by default in https://github.com/mapbox/mapbox-gl-js/pull/8053.

So it makes sense to remove that now.

**Comment by jparish3** [comment]
How is the proximity bias now set with trackProximity?

**Comment by andrewharvey** [comment]
> How is the proximity bias now set with trackProximity?

https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#parameters
`options.trackProximity`

When `trackProximity` is true (which is now the default in v4, then the proximity lon,lat will be automatically set based on the map center when the zoom is above a certain threshold.

It depends what kind of application your building on if you should disable or enable this as, I'd encourage you to do your own testing if this gives better or worse results. In my experience it weighs local results a bit too much, so I generally leave it disabled.
