### ISSUE TITLE
Incorrect styling in IE

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-geocoder#25]
<img width="284" alt="screen shot 2016-02-29 at 1 57 52 pm" src="https://cloud.githubusercontent.com/assets/7108211/13405470/84422cdc-deec-11e5-9a98-a77459c555e0.png">

Tested with Browserstack, Windows 10, IE 11

**Comment by drewbo** [comment]
@tristen do you have the svg used to create the icon-font reference? I have some experience with these not showing up in Windows (related to the `viewPort` tag) and can fix if you'd like

**Comment by tristen** [comment]
@drewbo thanks, that would be swell. Committed the icon source's here: https://github.com/mapbox/mapbox-gl-geocoder/commit/39bc1a2fc31349cc51811b342c60d760a205b403
