### ISSUE TITLE
Error "No mapboxgl detected in options. Map markers are disabled. Please set options.mapboxgl." with updated mapbox-gl and geocoder plugin

### ISSUE THREAD

**Issue by laurenoldham1202** [mapbox/mapbox-gl-geocoder#252]
I've recently upgraded to the most recent versions of mapbox-gl and plugins for my Angular 7 app and are currently as follows:

```
"@types/mapbox-gl": "^0.51.4",
"@mapbox/mapbox-gl-geocoder": "^4.0.0",
"mapbox-gl": "^0.53.1",
"ngx-mapbox-gl": "^3.1.0",
```

The pertinent and simplified code in my app is:
```
import * as M from 'mapbox-gl';
import * as GeoCoder from '@mapbox/mapbox-gl-geocoder';

  accessToken = 'TOKEN';
  geocoder: GeoCoder;
  map: M.Map;

 ngOnInit() {
    (M as any).accessToken = this.accessToken;

    this.map = new M.Map({
      container: 'map-catalog',
      style: 'mapbox://styles/mapbox/light-v9',  // tiles
      zoom: 1,
    });

    this.geocoder = new GeoCoder({
      accessToken: this.accessToken,
      placeholder: 'SEARCH GEOGRAPHY ON MAP',
    });
    this.map.addControl(this.geocoder);
  }
```

The final line of code in which I add the geocoder control to the map results in the console log error: 'No mapboxgl detected in options. Map markers are disabled. Please set options.mapboxgl.' 

Rolling back to @mapbox/mapbox-gl-geocoder v 3.1.0 removes that particular error, but results in a separate error about global being undefined. I'd like to use the most updated version regardless, so is there an easy fix for this?

**Comment by andrewharvey** [comment]
With v4.0.0 there's a new option `options.marker`, when true it will add a marker to the map based on the user's selection. To do this it needs the mapboxgl object passed as an option as well.

You can either disable the marker option, or pass the mapboxgl object as an option.

**Comment by laurenoldham1202** [comment]
Great! So the new code would be:

``` 
   this.geocoder = new GeoCoder({
      accessToken: this.accessToken,
      placeholder: 'SEARCH GEOGRAPHY ON MAP',
      marker: false,
      // mapboxgl: this.map,  // use this instead of 'marker: false' if you're going to use markers based on user selection
    });
```

**Comment by andrewharvey** [comment]
almost....

```js
import mapboxgl from 'mapbox-gl'
import 'mapbox-gl/dist/mapbox-gl.css'

const map = new mapboxgl.Map({ ...})
const geocoder = new MapboxGeocoder({
   mapboxgl: mapboxgl
})
```

the `map` variable is different to `mapboxgl` global.
