### ISSUE TITLE
Allow use of geocoder without map

### ISSUE THREAD

**Issue by yuletide** [mapbox/mapbox-gl-geocoder#270]
We've had a few requests for using `gl-geocoder` without any map component, which is not currently possible.

**Comment by antony** [comment]
This would be greatly helpful. for instance, in a search form, or on mobile, where there isn't always room for a map.

**Comment by jakobeissler** [comment]
This would be awesome!!

**Comment by scottsfarley93** [comment]
I started sketching out a solution to this over in #295. Would love feedback if anyone has thoughts on that approach.

**Comment by scottsfarley93** [comment]
This was added in #295 and will be included in the upcoming v4.5.0 release.
