### ISSUE TITLE
Local geocoder doesn't emit result event

### ISSUE THREAD

**Issue by scottsfarley93** [mapbox/mapbox-gl-geocoder#278]
In some cases, the localGeocoder will not emit a `result` event, which can cause a bad user experience, since the map will not zoom to the selected result. 

Steps to replicate:
1. Fire up this example: https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/
2. Search for "Park" 
3. Select one of the results
4.  Search for "Park" again
5. Select a new result --  notice that nothing happens

We should ensure that results from the localGeocoder are triggering all the events they should be. 

Note: this bug is present in v4.3.0, and so pre-dates the localGeocoder changes made in #275 and scheduled for v4.4.0 (#277). 

\cc @lobenichou

**Comment by scottsfarley93** [comment]
This was fixed in #298 and will be included in the upcoming v4.5.0 release.

**Comment by dehghani-mehdi** [comment]
@scottsfarley93 when you will release v4.5.0?
