### ISSUE TITLE
multiple local geocoder search results broken

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#281]
As reported at https://stackoverflow.com/questions/56579673/why-does-supplemental-mapbox-geocoder-allow-for-only-one-search in the example at https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/ if you:

1. Search and select Lincoln Park
2. Search and select Burnham Park.

Upon 2, it doesn't actually move to Burnham park, which it should.

**Comment by andrewharvey** [comment]
It looks like the issue could be around

https://github.com/mapbox/mapbox-gl-geocoder/blob/af44fb0f7458e709ec75ad7f8c1677f66f2ba84b/lib/index.js#L275

since localGeocoder sources may not have an id per feature set, we could either disable that where no id exists, or generate our own internal ids.

**Comment by scottsfarley93** [comment]
This looks to be the same as https://github.com/mapbox/mapbox-gl-geocoder/issues/278. It seems that the `result` event is not being emitted on subsequent selections from the local geocoder. 

@andrewharvey good point about the potential lack of IDs from the localGeocoder. As you point out, I could see how the lack of IDs could cause no `result` event to be generated.

**Comment by scottsfarley93** [comment]
This was fixed in #298 and will be included in the upcoming v4.5.0 release.
