### ISSUE TITLE
Search Results for Japan addresses are coming in Japanese language instead of English

### ISSUE THREAD

**Issue by girishts** [mapbox/mapbox-gl-geocoder#282]
Hi, 

Currently when we search any address of Japan ,
Search results are coming Japanese . How to get these search results auto complete in English

Thanks
Girish TS

**Comment by martinburch** [comment]
The underlying API query needs to be sent with `language=en`. You can set the parameter when making the geocoder instance...
```
new MapboxGeocoder({
accessToken: mapboxgl.accessToken,
mapboxgl: mapboxgl,
language: 'en'
})
```
...or by using the [`setLanguage() function`](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#setlanguage) later.

See [an example search for Osaka](https://docs.mapbox.com/search-playground/#{%22url%22:%22%22,%22index%22:%22mapbox.places%22,%22staging%22:false,%22onCountry%22:true,%22onType%22:true,%22onProximity%22:true,%22onBBOX%22:true,%22onLimit%22:true,%22onLanguage%22:true,%22countries%22:[],%22proximity%22:%22%22,%22typeToggle%22:{%22country%22:false,%22region%22:false,%22district%22:false,%22postcode%22:false,%22locality%22:false,%22place%22:false,%22neighborhood%22:false,%22address%22:false,%22poi%22:false},%22types%22:[],%22bbox%22:%22%22,%22limit%22:%22%22,%22autocomplete%22:true,%22languages%22:[{%22code%22:%22en%22,%22name%22:%22English%22}],%22languageStrict%22:false,%22onDebug%22:false,%22selectedLayer%22:%22%22,%22debugClick%22:{},%22localsearch%22:false,%22query%22:%22osaka%22}) in the playground.

**Comment by girishts** [comment]
Thanks @martinburch   :)
It worked after adding language parameter
