### ISSUE TITLE
Dragable After Search Location

### ISSUE THREAD

**Issue by Muhammad-Umair07** [mapbox/mapbox-gl-geocoder#312]
How can we enable draggable after searching a location to populate lat longs on drag?

```
var mapbox_marker = new mapboxgl.Marker({draggable: true, color: 'orange'}).setLngLat([get_strings.map_long, get_strings.map_latt]).addTo(mapz);
						function onDragEnd() {
							var lngLat = mapbox_marker.getLngLat();
							//console.log(lngLat);
							document.getElementById('property_latt').value = lngLat.lat;
					 		document.getElementById('property_long').value = lngLat.lng;
						}
						mapbox_marker.on('dragend', onDragEnd);
						var geocoder = new MapboxGeocoder({
								accessToken: mapboxgl.accessToken,
								zoom: 13,
								marker: {
									color: 'orange',
									draggable: true
								},
								mapboxgl: mapboxgl
					  });
						mapz.addControl(geocoder);
```

**Comment by andrewharvey** [comment]
Sorry I don't understand what you're asking, could you elaborate?

**Comment by Muhammad-Umair07** [comment]
> 
> 
> Sorry I don't understand what you're asking, could you elaborate?

Hi, 

I mean to say how can we enable marker on map after searching an address using geocoder. So after selected location user can adjust his location using marker drag to get latt and longs.

Thanks

**Comment by Muhammad-Umair07** [comment]
I am talking about this one https://docs.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/ 
Whenever we search a place it redirects us to that particular location with a marker sign. So I want to enable that marker to get latt longs if the user moves that marker.

Thanks

**Comment by andrewharvey** [comment]
Yep so if you just use https://docs.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/ and add `draggable: true` as the marker option under color, then you can drag the marker.

When you say get the lat longs after the user moves the marker, get them where?

To do that, just listen to the marker dragend event https://docs.mapbox.com/mapbox-gl-js/api/#marker.event:dragend

eg. `geocoder.mapMarker.on('dragend', (e) => { console.log(e.target.getLngLat()); });
`

**Comment by Muhammad-Umair07** [comment]
> 
> 
> Yep so if you just use https://docs.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/ and add `draggable: true` as the marker option under color, then you can drag the marker.
> 
> When you say get the lat longs after the user moves the marker, get them where?
> 
> To do that, just listen to the marker dragend event https://docs.mapbox.com/mapbox-gl-js/api/#marker.event:dragend
> 
> eg. `geocoder.mapMarker.on('dragend', (e) => { console.log(e.target.getLngLat()); }); `

Thanks for your help it's working now

**Comment by justwooper** [comment]
Hi, I need to implement the same, but I couldn't find mapMarker after geocoder, is something changed?, is that not the same function? could you help me?

**Comment by andrewharvey** [comment]
> Hi, I need to implement the same, but I couldn't find mapMarker after geocoder, is something changed?, is that not the same function? could you help me?

Although it should work, I shouldn't be promoting it since it's a private undocumented property. I think the cleanest approach is not use mapbox-gl-geocoder's provided Marker, but instead create your own, that way you have full control over it.

If you want to piggyback off the built in geocoder marker then .mapMarker should still work.

If you can post a minimal example demonstrating your issue I might be able to take a look.

**Comment by justwooper** [comment]
mmm just thinking using geocoder.on('result' function, and when i get result variable, insert a marker in the map, is there a way not to add the default marker that comes in geocoder? so I can insert manually the marker?

**Comment by justwooper** [comment]
nevermind, just read that if you put marker: false, it doesnt put the marker, thanks

**Comment by tivui64** [comment]
I have the same problem: obtain a draggable marker with dragend event after search. No example who works on the net... Is it possible? Thanks a lot for your answer.

**Comment by andrewharvey** [comment]
> I have the same problem: obtain a draggable marker with dragend event after search. No example who works on the net... Is it possible? Thanks a lot for your answer.

Absolutely it's possible:

```js
  const geocoder = new MapboxGeocoder({
      mapboxgl: mapboxgl,                                                                               
      accessToken: mapboxgl.accessToken,
      marker: false
    })
    geocoder.on('result', e => {
      const marker = new mapboxgl.Marker({
        draggable: true
      })
      .setLngLat(e.result.center)
      .addTo(map)
    })
    map.addControl(geocoder)
```

**Comment by vjtheprogrammer** [comment]
Hii guys.. I have done the best solutions for you all.. You can **Create a Dragable marker After Search Location result.** 
I have also **separate the search bar outside the map**. Check the attached **.docx file.**

[Create a draggable Marker after Geocoder search result from outside the map.docx](https://github.com/mapbox/mapbox-gl-geocoder/files/5679247/Create.a.draggable.Marker.after.Geocoder.search.result.from.outside.the.map.docx)

**Comment by luispv02** [comment]
hello, I was looking for something like this, when using the code, it leaves a marker in each location, is there a way to avoid this?
