### ISSUE TITLE
Geocoder country code inconsistency

### ISSUE THREAD

**Issue by diegogarciar** [mapbox/mapbox-gl-geocoder#321]
Hello,
I'm not sure if its a bug or it has its reason but the geocoder usually returns an uppercased iso-2 country code for all countries except US, which returns the country code lowercased. Is there a reason for this?

**Comment by andrewharvey** [comment]
Hi, this is the issue tracker for mapbox-gl-geocoder which is a UI control for putting a search box on a Mapbox GL JS map. It looks like your question relates to the Mapbox Geocoding API? If that's the case this isn't the right place for questions relating to the geocoding API, best reach out to Mapbox support https://www.mapbox.com/contact/.
