### ISSUE TITLE
[v4.5.0] Geocode localGeocoder should prevent calling api.mapbox.com

### ISSUE THREAD

**Issue by dehghani-mehdi** [mapbox/mapbox-gl-geocoder#323]
Hi,

When using `localGeocoder`, MapboxGeocoder should not call `api.mapbox` anymore. 

```
new MapboxGeocoder({
  accessToken: MapboxGL.accessToken,
  mapboxgl: MapboxGL,    
  localGeocoder: forwardGeocoder
})       
```

When I enter, for example, `xyz` in searchbox, the `forwardGeocoder` called successfully, but at the end MapboxGeocoder makes call to `api.mapbox` and show the result of this call instead of provided info by `forwardGeocoder`.

**Comment by andrewharvey** [comment]
Per the [API docs](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md) the `localGeocoder` option "performs local geocoding to supplement results from the Mapbox Geocoding API." So it's designed to supplement not replace the Mapbox Geocoding API.

The results passed back from the localGeocoder should still be appearing on top of the results with those from Mapbox below.

**Comment by dehghani-mehdi** [comment]
Is there any way to disable mapbox's api call?

> The results passed back from the localGeocoder should still be appearing on top of the results with those from Mapbox below.

Nope, the result of `localGeocoder` doesn't show up.

**Comment by andrewharvey** [comment]
> Is there any way to disable mapbox's api call?

Oh yes the `localGeocoderOnly` option can be set to true.

> Nope, the result of localGeocoder doesn't show up.

Could you post a minimal example demonstrating the issue?

**Comment by dehghani-mehdi** [comment]
> Oh yes the localGeocoderOnly option can be set to true.

Thanks man, it did the job.

> Could you post a minimal example demonstrating the issue?

That was my mistake, I'm sorry.

I have another question though, everytime I enter a character into search textbox, geocoder calls `localGeocoder` method and it doesn't provide great ux, is there anyway to increase this time or I have to handle it by myself?

**Comment by andrewharvey** [comment]
> I have another question though, everytime I enter a character into search textbox, geocoder calls localGeocoder method and it doesn't provide great ux, is there anyway to increase this time or I have to handle it by myself?

Not sure exactly what you mean. `minLength` says how many chars before we start trying to geocode. Apart from this the library has a built in 200ms debounce to avoid a rapid fire of keystrokes making too many requests or calls to your localGeocoder.

**Comment by dehghani-mehdi** [comment]
@andrewharvey that `debounce` time.

Imagine user want to find location with name `abc`, when user type `ab` geocoder calls localGeocoder and show the indicator and prevent user to type next character, e.g: `c`, user only able to enter/type next character only at the end of prev call.

increasing `minLength` doesn't help here. that `debounce` time should be the solution. I didn't find anyway to control this time in docs. is there anyway to change this value?

**Comment by andrewharvey** [comment]
> Imagine user want to find location with name abc, when user type ab geocoder calls localGeocoder and show the indicator and prevent user to type next character, e.g: c, user only able to enter/type next character only at the end of prev call.

I can't replicate that in the example at https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/

**Comment by dehghani-mehdi** [comment]
Because that example uses hard-coded json object (customData) and parsing that is too fast. I make ajax _synchronous_ call inside my localGeocoder method.

**Comment by andrewharvey** [comment]
"Synchronous requests block the execution of code which causes "freezing" on the screen and an unresponsive user experience." that's the nature of something synchronous and why you probably should be using an asynchronous request.

An async external geocoder to work in tandem with the Mapbox Geocoding API and the localGeocoder is proposed at #165 but still needs some work before it's ready. Feel free to help out.

**Comment by dehghani-mehdi** [comment]
Yes, that's true.
Because I saw #157, I use synchronous ajax (it's very bad, I know). I want to improve the behavior until async support adds to the geocoder.

> Feel free to help out.

I love to help and I'll if I can.

Thank you for your time and help.
