### ISSUE TITLE
it's not possible to initialize geocoder on a specific point

### ISSUE THREAD

**Issue by Songissimo** [mapbox/mapbox-gl-geocoder#329]
I would like to restore a previously searched position on the map through the geocoder. At the moment this is not possible unless I search for the id of the feature previously found but in this way I get a different place name.

How can this be sorted out?
Thanks

**Comment by andrewharvey** [comment]
I'm not sure exactly what you're asking, could you elaborate on how you'd like this to work and share an example?

**Comment by Songissimo** [comment]
I need to initialize the geocoder on a specific search result (identified by an id) in order to show it as a point on the map.

**Comment by Dylansc22** [comment]
@Songissimo , I think we are having the same question! Did you figure this out?

When a geocoder search is "triggered", "engaged", "queried"... etc... I want to save data from the search result marker to a new array (mainly lat long, name, address)... And I dont know how to write the code to occur when that geocoder event is "triggered"

In pseudo-code I'm imagining its something like:
``` 
geocoder.AddEventListener("onQuery, myFunction);
myFunction(){
var x = geocoder.mapMarker._lngLat //save the coordinates of the search result marker
//other code playing with x
}
```

Any ideas?

**Comment by andrewharvey** [comment]
> I need to initialize the geocoder on a specific search result (identified by an id) in order to show it as a point on the map.

@Songissimo So you want to trigger the geocoder, I guess you could use setInput? https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#setinput


@Dylansc22 for your use case you'll probably want to listen to the results event https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#on eg.

```js
geocoder.on('results', e => {
  console.log(e)
})
```

**Comment by andrewharvey** [comment]
I'll close this out because I can't see anything addressable, but feel free to post back if that's not right.
