### ISSUE TITLE
The Gl-Geocoder Demo Auto Complete Does not work on Copy/pasting Addresses

### ISSUE THREAD

**Issue by shabnomnom** [mapbox/mapbox-gl-geocoder#330]
Per conservation, with @scottsfarley93 this issue is been resolved in[ version 4.5.0 of the GL geocoder library](https://github.com/mapbox/mapbox-gl-geocoder). The [Mapbox GL-Geocoder demo](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/) in our documentation does not reflect this update.

**Comment by andrewharvey** [comment]
:wave: hi @shabnomnom the example update is happening over at https://github.com/mapbox/mapbox-gl-js-docs/pull/115.

**Comment by andrewharvey** [comment]
I'll close this now that https://github.com/mapbox/mapbox-gl-js-docs/pull/115 was merged.
