### ISSUE TITLE
Passing custom instance of Marker to geocoder

### ISSUE THREAD

**Issue by admly** [mapbox/mapbox-gl-geocoder#331]
Hello. Im trying to do something like this:
```

    this.marker = new mapboxgl.Marker({draggable: true, color: 'orange'});
    this.marker.setDraggable(true);

    this.map.on('load', () => {
      this.geocoder = new MapboxGeocoder({
        accessToken: mapboxgl.accessToken,
        marker: this.marker,
        mapboxgl: mapboxgl
      });
      this.map.addControl(this.geocoder);
    });

```

Unfortunately, geocoder keeps on setting a default marker. I just want to have the geocoder marker draggable and I want to be able to read a location from it and I tried to achieve it by passing a custom marker, but it doesn't work :( I'd be thankful if anyone can explain to me how I can code this.

**Comment by andrewharvey** [comment]
According to the API documentation at https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#parameters

> options.marker (Boolean | Object) If true, a Marker will be added to the map at the location of the user-selected result using a default set of Marker options. **If the value is an object, the marker will be constructed using these options.** If false, no marker will be added to the map. Requires that options.mapboxgl also be set. (optional, default true)

**Comment by andrewharvey** [comment]
ie. pass the marker option `{draggable: true, color: 'orange'}` and not the `new Marker` instance.

**Comment by admly** [comment]
@andrewharvey
I already read this documentation. As I wrote, I'd like to have a reference to a marker, to read it's coordinates. So for example someone types an address, geocoder sets a marker, someone is adjusting the marker by himself and then coordinates of marker are read. Is it possible? Or maybe it could be added as a new feature?

**Comment by andrewharvey** [comment]
So you can get the Marker reference through `geocoder.mapMarker` but this is not part of the public API so could change in any future version without notice. I think it's a good suggestion, my preference is a new method `geocoder.getMarker()` which returns the marker reference or null.

Need to think about the fact that the marker reference will only exist when a marker is on the map so there's a timing issue, and issue trying to access it once the geocoder has removed it. Also each new search will change the reference. So it's not so straightforward and requires a lot of consideration. If you want to help out, feel free to make a new ticket for the feature request, or with a PR, I'd be happy to help review it.

Of course you could always turn off the marker with `marker: false` and create your own on the geocoder events, that way you have full control.
