### ISSUE TITLE
How do I get the coordinates, for the geocoder result?

### ISSUE THREAD

**Issue by Magnuspil** [mapbox/mapbox-gl-geocoder#334]
Hi,

I wish to get the coordinates, from the marker placed when using Geocoder with mapbox. As a start, it would be great to be able to output it to console, from there i should be able to do what I need. 

Thank you in advance, for your help!

**Comment by andrewharvey** [comment]
See https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#on

```js
geocoder.on('result', function(e) {
})
```

**Comment by Magnuspil** [comment]
Hi Andrew,

Thank you for your quick answer. 

I was on that so far, the part i have the specific issue with, is fetching the actual coordinates on the selected results. Would i use get proximity to fetch it so?

Thank you,
Magnus

**Comment by andrewharvey** [comment]
```js
geocoder.on('result', function(e) {
  console.log(e.result.center)
})
```

**Comment by Magnuspil** [comment]
> ```js
> geocoder.on('result', function(e) {
>   console.log(e.result.center)
> })
> ```

Hello Andrew,

Thank you for your solution.  Is it possible to separate the in to strings? Could it possible be something like this: `e.result.center.latitude` & `e.result.center.longitude`?

A little side question: I have a marker, added with a click function. I already got the geocoder to remove click-marker when placing a geocode marker, but I tried the other way around, removing geocode marker on click - no luck. Tried the following: `geocoder.marker.remove();`

How would you go about that?

**Comment by andrewharvey** [comment]
@Magnuspil best to contact Mapbox Support for support.

**Comment by josecordova** [comment]
e.result.center[0];
e.result.center[1];

> > ```js
> > geocoder.on('result', function(e) {
> >   console.log(e.result.center)
> > })
> > ```
> 
> Hello Andrew,
> 
> Thank you for your solution. Is it possible to separate the in to strings? Could it possible be something like this: `e.result.center.latitude` & `e.result.center.longitude`?
> 
> A little side question: I have a marker, added with a click function. I already got the geocoder to remove click-marker when placing a geocode marker, but I tried the other way around, removing geocode marker on click - no luck. Tried the following: `geocoder.marker.remove();`
> 
> How would you go about that?
