### ISSUE TITLE
A simple method with coords that returns the location data?? - Programmable geocoder request or query without having to use the ui input.

### ISSUE THREAD

**Issue by veratechnz** [mapbox/mapbox-gl-geocoder#336]
Why does the geocoder api not have a simple and clear method() for developers to make a query with coordinates and have a data object returned. There are several variations of how to do this with people using: 

- mapbox-js-sdk
- an offshoot of the mapboxClient.reverseGeocode()
- using a get request with the actual api string call _(I ended up using this)_

I would have thought users wanting to send coords **_in code_** with location data subsequently returned would have been a common use case. Curious why this hasn't been added as a simple method onto the _geocode api_ and documented. A looong time online searching for a code sample with a workable and logical solution. My final code below (_pk.ey is the beginning of the mapbox access token_):

![image](https://user-images.githubusercontent.com/7610017/73617609-4aef1a80-4685-11ea-9371-4ebe87712b10.png)

**Comment by andrewharvey** [comment]
This project provides a graphical search input as a control for mapbox-gl. It uses [mapbox-sdk-js](https://github.com/mapbox/mapbox-sdk-js) which in turn uses the [Mapbox Geocoding REST API](https://docs.mapbox.com/api/search/).

If you don't want any of the user interface and just want to make calls from JavaScript, then you should use https://github.com/mapbox/mapbox-sdk-js. It's also fine to use the REST API directly, but the Mapbox SDK for JS wraps this with a nice interface.

**Comment by veratechnz** [comment]
Thanks for the quick response.

Your main entry point into the mapbox API and the majority of your documentation references the geocoding object i.e. (mapbox-gl) and the associated user interface. Why not bolt on a simple method instead of getting users to download an additional module i.e. mapbox SDK JS. The user interface within mapbox-gl is comprehensive including 20 or so additional methods. The mapbox-gl-geocoder must be making API calls and wouldn't it be easy to add this kind of method (aforementioned) for users and document accordingly?

**Comment by andrewharvey** [comment]
> Your main entry point into the mapbox API and the majority of your documentation references the geocoding object i.e. (mapbox-gl) and the associated user interface.

Sorry I'm not sure what you mean. https://docs.mapbox.com/api/search/#geocoding actually points directly to mapbox-sdk-js and not mapbox-gl-gecoder.

> Why not bolt on a simple method instead of getting users to download an additional module i.e. mapbox SDK JS. The user interface within mapbox-gl is comprehensive including 20 or so additional methods. The mapbox-gl-geocoder must be making API calls and wouldn't it be easy to add this kind of method (aforementioned) for users and document accordingly?

My personal opinion is it's better to keep this library focused as a UI control, and leave direct JS access to mapbox-sdk-js. Including it here would increase the code complexity and maintenance effort.

**Comment by veratechnz** [comment]
Thanks Andrew, I get that having the mapbox js-sdk may assist in separating the logic etc. At least in this discussion you have some context of one developer's journey. 

Happy that I have a working solution for coords -> geocoding data as a result in javascript.
