### ISSUE TITLE
Icons not visible in IE11

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-geocoder#340]
None of the SVG icons are visible in IE11. -Geolocate icon not visible in Mobile Safari- (`GeolocateControl` is a MapboxGL Object)

Apparently IE doesn't allow to use ìnnerHTML on SVG nodes. This is how React got around that: https://github.com/facebook/react/blob/8e0c574122b3d3eadcffaec1223e95d479b01c6e/packages/react-dom/src/client/setInnerHTML.js

**Comment by andrewharvey** [comment]
closed by #341.
