### ISSUE TITLE
Use localGeocoder for searching my points/markers

### ISSUE THREAD

**Issue by resekartan** [mapbox/mapbox-gl-geocoder#349]
Hello. How can I use a localGeocoder to search for points/markers in my dataset/tilset?

**Comment by andrewharvey** [comment]
You can use the [Mapbox SDK for JS](https://github.com/mapbox/mapbox-sdk-js/) to [list all the features in your Dataset](https://github.com/mapbox/mapbox-sdk-js/blob/master/docs/services.md#listfeatures), form there you can follow the example at https://docs.mapbox.com/mapbox-gl-js/example/forward-geocode-custom-data/ but using your data from your Dataset as the localGeocoder source.
