### ISSUE TITLE
"No results found" text is hardcoded

### ISSUE THREAD

**Issue by jRexhmati** [mapbox/mapbox-gl-geocoder#360]
The function _renderNoResults is pretty static and it gives no chance to change the message neither the whole template if needed

**Comment by andrewharvey** [comment]
#328 would provide the capability to set your own text, so I'm tempted to close this issue and keep the discussion on the existing ticket.

To change the formatting or remove it the element has the CSS class `mapbox-gl-geocoder--error mapbox-gl-geocoder--no-results` so you could provide your own CSS to restyle it.

**Comment by luisdnodrizat** [comment]
CSS solution:
`.mapbox-gl-geocoder--no-results {
    display: none;
}`
