### ISSUE TITLE
Geocoder doesn't find places which exist in OSM

### ISSUE THREAD

**Issue by mariusa** [mapbox/mapbox-gl-geocoder#372]
Hi,

Using the example at
https://docs.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/
search for "Porumbacu de Sus"

It gives only irrelevant results, which are completely unrelated to this name: Stingray, Sushi Sumo... 

The same search works on OSM: https://www.openstreetmap.org/search?query=Porumbacu%20de%20Sus#map=14/45.7138/24.4734

This is incredibly poor and makes Geocoder unusable for us. Would you consider fixing this?

![Screenshot from 2020-06-23 19-42-07](https://user-images.githubusercontent.com/1283842/85431413-30f99a00-b58a-11ea-86e3-d2d5ca784558.png)
![Screenshot from 2020-06-23 19-42-28](https://user-images.githubusercontent.com/1283842/85431419-31923080-b58a-11ea-8a61-8d841ad70cbe.png)

**Comment by andrewharvey** [comment]
Hi — thanks for using Mapbox. This repo is for reporting issues, requesting features, and coordinating work related to the Mapox GL JS Geocoder, which is a user interface wrapper around the Mapbox Geocoding API for Mapbox GL JS. Issues relating to the Mapbox Geocoding API aren't actionable by this repository, so please reach out to the excellent [support team](https://www.mapbox.com/contact/support/) instead.

**Comment by mariusa** [comment]
FYI the excellent support team didn't even reply to the ticket opened 7 days ago. I followed up 2 days ago with more examples, no reply.
