### ISSUE TITLE
clearOnBlur doesn't work, leaves previous location in the input

### ISSUE THREAD

**Issue by mariusa** [mapbox/mapbox-gl-geocoder#374]
Goal: After user types a destination and selects it from the list, we process the result. The input field should be cleared, waiting to search for another destination.
```
this.geocoder.on('result', this.geocoderResult)
```

Using the example at https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/
added this option:
```
clearOnBlur: true,
```
but it has no effect: https://jsfiddle.net/uj8kbfm2/

Is my goal not intended for ```clearOnBlur```, and instead should clear the input in  ```this.geocoderResult()``` ?

**Comment by andrewharvey** [comment]
> but it has no effect: https://jsfiddle.net/uj8kbfm2/

When a result is selected, the input element remains focused so it's not being cleared, only then when you click somewhere else outside the input does it trigger the blur and clear (with `clearOnBlur`). So in that regard `clearOnBlur` is working as intended.

#368 discusses if selecting the result should still keep the input focused or not. So if the outcome of that is not to remain focused, it should address your concerns.

Though there is still a difference between having a cleared input vs just making it not focused.

The default behaviour places a marker at the selected result and in that case I think it makes sense to retain the place name in the search input as it reflect what's selected and provides a way to clear it. I also agree for some other use cases once selected you'd want the field cleared.

Would it work if you listen to result and the clear? eg
```js
geocoder.on('result', () => {
  geocoder.clear()
})
``

**Comment by mariusa** [comment]
> Would it work if you listen to result and the clear

Yes, that's great! Appreciate your help, Andrew!
