### ISSUE TITLE
fix build failure blocking release

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#379]
```
# Geocoder--no map
# result was added to container
not ok - this is undefined
http://localhost:40937/script.js:448
      const el = this.onAdd(); //returns the input elements, which are then added to the requested html container
             ^
```

https://github.com/mapbox/mapbox-gl-geocoder/pull/353

**Comment by andrewharvey** [comment]
due to a change introduced in #311. looks like function may need to be bound to this. It was before but that was dropped in the PR.

**Comment by andrewharvey** [comment]
alternatively we can revert #311 which takes the pressure off fixing this issue see https://github.com/mapbox/mapbox-gl-geocoder/pull/311#issuecomment-657163138.

Myself I don't have the time to properly fix the issue but also would like to see the other bug fixes make a release so if there's no fix soon I might opt to revert those changes out of master back into a PR to unblock the release.

**Comment by antony** [comment]
Ok, I've fixed/corrected/removed the various test failures + functionality.
