### ISSUE TITLE
Empty published dist/mapbox-gl-geocoder.min.js

### ISSUE THREAD

**Issue by elygeo** [mapbox/mapbox-gl-geocoder#384]
Hi, For the v4.6 the minified JS file on NPM is empty.

https://unpkg.com/@mapbox/mapbox-gl-geocoder@4.6.0/dist/mapbox-gl-geocoder.min.js

**Comment by andrewharvey** [comment]
@tristen maybe this means the `npm run prepublish` step at https://github.com/mapbox/mapbox-gl-geocoder/blob/master/CONTRIBUTING.md#deploying might not have been run before the `npm publish`?

Also looks like https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.6.0/mapbox-gl-geocoder.min.js wasn't deployed.

**Comment by 3zzy** [comment]
@andrewharvey Sorry, is something being done about this?

**Comment by andrewharvey** [comment]
@3zzy not much I can do since I don't have permissions to publish to NPM or the CDN.

**Comment by tristen** [comment]
🙈 sorry folks. I'll get a patched version together to address this now.

**Comment by tristen** [comment]
👋 Published `4.7.0` to npm with the dist directory (https://unpkg.com/@mapbox/mapbox-gl-geocoder@4.7.0/dist/mapbox-gl-geocoder.min.js)
