### ISSUE TITLE
reverse & forward geocodes are not in sync & reverse is incorrect

### ISSUE THREAD

**Issue by jparish3** [mapbox/mapbox-gl-geocoder#387]
the forward geocode request for 1800 Queens Road West, Charlotte, North Carolina 28207, United States provides the correct address & coordinates. the reverse geocode request for the address coordinates":[-80.8393329,35.1818526] returns 1800 Queens Road West, Charlotte, North Carolina **28209,** United States, which contains an incorrect postal code. this occurs for all addresses within this area and presumably any US area near postal code boundaries. This issue can be easily observed at [https://docs.mapbox.com/search-playground/](url)

**Comment by andrewharvey** [comment]
Since this is an issue with the Mapbox Geocoding API, best to contact Mapbox Support mapbox.com/support.

This repository is only for the Mapbox GL JS plugin which only provides the user interface wrapper on top of the API, so it's not something that can be addressed in this repo.
