### ISSUE TITLE
Add option to disable autocomplete

### ISSUE THREAD

**Issue by JoeyPriceless** [mapbox/mapbox-gl-geocoder#397]
Since rate limits to geocoding services often are very strict, it would be great if there was an option to disable autocomplete. I thought that I would be able to increase minLength to a large number such as 1000 but then the control does not work at all.

**Suggestion**
Add an option to disable autocomplete. Then, if autocomplete is disabled and the user presses enter, serve the first result. This might also be the desired behavior if autocomplete is enabled and user presses enter while query is shorter than minLength.

**Comment by JoeyPriceless** [comment]
I would happily add this change myself if this fits within your vision of the project.

**Comment by mpothier** [comment]
Added in #434
