### ISSUE TITLE
MapBox geocode controller: how to disable automatic zoom into location?

### ISSUE THREAD

**Issue by kevinmachstudio** [mapbox/mapbox-gl-geocoder#40]
For MapBox geocoderControl API, how do you prevent the map from zooming in when the user enters a location? For example, right now if I search for New York, the map zooms into New York. I want the map to stay where it is and avoid setting the view again since that transition from zooming in and resetting very quickly causes the page to flash, which could be a nuisance for the user. I'm using geocoderControl.on('select') method.

**Comment by tristen** [comment]
You can pass `flyTo:false` in the initial options. i.e 

``` js
map.addControl(new mapboxgl.Geocoder({
  flyTo: false 
}));
``` 

And see https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#mapboxglgeocoder for more options.
