### ISSUE TITLE
Create a Dragable marker After Search Location result. Also separate the search bar outside the map

### ISSUE THREAD

**Issue by vjtheprogrammer** [mapbox/mapbox-gl-geocoder#405]
Hii guys.. I have done the best solutions for you all.. You can **Create a Dragable marker After Search Location result.**
I have also **separate the search bar outside the map**. Check the attached **.docx file.**

[Create a draggable Marker after Geocoder search result from outside the map.docx](https://github.com/mapbox/mapbox-gl-geocoder/files/5679271/Create.a.draggable.Marker.after.Geocoder.search.result.from.outside.the.map.docx)

**Comment by maulayyacyber** [comment]
thanks @vjtheprogrammer
