### ISSUE TITLE
Typing semicolon in the geocoder causes an error

### ISSUE THREAD

**Issue by jakub-leszczynski** [mapbox/mapbox-gl-geocoder#408]
Hey!

The easiest way to reproduce is to:

1.  Navigate to geocoder example page here: https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/
2. Open the console to see error message
3. Type anything followed by a semicolon.
4. See the following message:
![Screenshot 2020-12-29 at 16 20 59 (2)](https://user-images.githubusercontent.com/26040789/103294531-514f5900-49f2-11eb-88ec-a12ea7e0b635.png)
![Screenshot 2020-12-29 at 16 20 46 (2)](https://user-images.githubusercontent.com/26040789/103294540-557b7680-49f2-11eb-9622-6f5230aa0ade.png)

I've been trying other signs but only the semicolon seems to be causing the issue.
I've also been able to reproduce this locally.

**Comment by andrewharvey** [comment]
#352 was mostly for where a coordinate pair would create an error, but it could apply here. All we could do on the mapbox-gl-geocoder side is try and detect an error before the call is made and not make the call. Otherwise what else would you expect to happen here?
