### ISSUE TITLE
impossible to install with NPM because of broken dependency tree

### ISSUE THREAD

**Issue by jimblue** [mapbox/mapbox-gl-geocoder#414]
Hi,

It's actually impossible to install **mapbox-gl-geocoder**  with the latest **mapbox-gl** because peer dependency are too low `mapbox-gl@">= 0.47.0 < 2.0.0"`

One of your latest commit https://github.com/mapbox/mapbox-gl-geocoder/commit/75187f9d24cf2d620a57dcfe0e9e7ad6710470bc should fix it, so can you please publish a new NPM release.

Thank you 😄

**Comment by eltoro** [comment]
Is this fixed published? I still get a peer dependency error trying to install 4.7.1:

Could not resolve dependency:
peer mapbox-gl@">= 0.47.0 < 2.0.0" from @mapbox/mapbox-gl-geocoder@4.7.0
