### ISSUE TITLE
"Uncaught TypeError: EventEmitter is not a constructor" using vite

### ISSUE THREAD

**Issue by fc** [mapbox/mapbox-gl-geocoder#441]
Steps:
1. Instantiate mapbox-gl-geocoder

Reproduce it here:
https://replit.com/join/qyvahtyiuq-fc14

Or refer to this code snippet:

```
import React from 'react';
import MapboxGeocoder from '@mapbox/mapbox-gl-geocoder';
import './App.css';

function App() {
  new MapboxGeocoder({
            accessToken: '',
            mapboxgl: '',
            marker: false,
          });
  return (
    <main>
      React⚛️ + Vite⚡ + Replit🌀
    </main>
  );
}

export default App;
```

Current:
```
Uncaught TypeError: EventEmitter is not a constructor
    at new MapboxGeocoder (index.js?b9d5:43)
...
```

Expected:
No error

Seems like this is because I'm using vite as this worked previously.
`events` is also not listed as a dependency.

Temporary workaround:
Install `events`
```
pnpm install events @types/events
```

**Comment by CyrilAnac** [comment]
Same issue, @fc thanks for the workaround

**Comment by janosh** [comment]
So the problem is that `mapbox-gl-geocoder` needs to specify `events` as a dep? But then why would it work outside `vite`?

**Comment by mbullington** [comment]
Vite doesn't natively do the Node emulation that other bundlers do. See Parcel docs for these examples: https://parceljs.org/features/node-emulation/

This is still our bug—per say. We should include https://www.npmjs.com/package/events in the dependencies.

Thanks!

**Comment by shreyaa12** [comment]
I am using React and trying to remove CRA from the existing app and transition from react scripts to webpack.
ncaught TypeError: EventEmitter is not a constructor
    at eval (emitter.js:2:18)
    at ./node_modules/webpack/hot/emitter.js (bundle.js:39:1)
    at __webpack_require__ (bundle.js:176:32)
    at fn (bundle.js:371:21)
    at eval (index.js:10:80)
    at ./node_modules/webpack-dev-server/client/index.js?
