### ISSUE TITLE
Set default value but not search

### ISSUE THREAD

**Issue by pauldunstone** [mapbox/mapbox-gl-geocoder#455]
Hi there
Is there a way to set a default value for the input but not to perform a search? For example, if the user has already searched for a location and we know their preferred location we want to set the value of the input to default to their preferred location. 
If we use geocoder.setInput('London') for example, the control performs a search.
There is the placeholder text but this isn't really ideal.
Cheers, Paul

**Comment by rocknatt** [comment]
I face the same problem too.

**Comment by ericlighthofmann** [comment]
Seems like this was supposed to be fixed in #425 but not sure if that's still happening. 

To note - if you want the X clear back after ._setInputValue(), use:
`$('.mapboxgl-ctrl-geocoder--button').show();`

**Comment by pauldunstone** [comment]
You can however set the value on your control using Javascript and it won't perform the search i.e.

$(".mapboxgl-ctrl-geocoder--input").val('London');
