### ISSUE TITLE
[Feature Request] Be able to only use the api

### ISSUE THREAD

**Issue by JeremieBergeron** [mapbox/mapbox-gl-geocoder#466]
Currently, mapbox-gl-geocoder can only be use to create the dropdown.

I would want to directly communicate with the api.

Of course, I can create manually a url (like this https://api.mapbox.com/geocoding/v5/mapbox.places/EXAMPLE.json?limit=10&proximity=ip&types=place&language=fr&autocomplete=true&access_token=MYTOKEN), but it is always a nice to have to be able to customize our url from an object.

**Comment by andrewharvey** [comment]
Best to use https://github.com/mapbox/mapbox-sdk-js then as this project is for the UI frontend only.

**Comment by JeremieBergeron** [comment]
Sorry, I did not saw this package.

Thank you!
