### ISSUE TITLE
Error 422 not handled for invalid values

### ISSUE THREAD

**Issue by pastcompute** [mapbox/mapbox-gl-geocoder#47]
I had a typo in my 'options' - specifically, I used "AU" for the country code instead of 'au'

The only indication that there is a problem, as seen in the browser console is:

```
Error: Uncaught, unspecified "error" event. ([object Object])
[2]</n.prototype.emit()
 mapbox-gl-geocoder.js:1
[1]</n.prototype<.fire()
 mapbox-gl-geocoder.js:1
[1]</n.prototype<._geocode/this.request.onload<()
 mapbox-gl-geocoder.js:1
bound ()
 self-hosted:752
```

Eventually I thought to check the network tab in the debugger where I found the underlying error:

```
message:"Stack "AU" is not a known stack. Must be one of: cn, jp, au, nz, sg, kr, br, ca, at, be, ch, de, dk, es, fi, fr, it, nl, no, se, gb, ie, us, af, ax, al, dz, as, ad, ao, ai, aq, ag, ar, am, aw, az, bs, bh, bd, bb, by, bz, bj, bm, bt, bo, ba, bw, bv, bn, bg, bf, bi, kh, cm, cv, ky, cf, td, cl, cx, co, km, cg, cd, ck, cr, ci, hr, cu, cw, cy, cz, dj, dm, do, ec, eg, sv, gq, er, ee, et, fk, fo, fj, gf, pf, tf, ga, gm, ge, gh, gi, gr, gl, gd, gp, gu, gt, gg, gn, gw, gy, ht, va, hn, hk, hu, is, in, id, ir, iq, im, il, jm, je, jo, kz, ke, ki, kp, kw, kg, la, lv, lb, ls, lr, ly, li, lt, lu, mo, mk, mg, mw, my, mv, ml, mt, mh, mq, mr, mu, yt, mx, fm, md, mc, mn, me, ms, ma, mz, mm, na, nr, np, nc, ni, ne, ng, nu, nf, mp, om, pk, pw, ps, pa, pg, py, pe, ph, pn, pl, pt, pr, qa, re, ro, ru, rw, bl, sh, kn, lc, mf, pm, vc, ws, sm, st, sa, sn, rs, sc, sl, sx, sk, si, sb, so, za, gs, ss, lk, sd, sr, sj, sz, sy, tw, tj, tz, th, tl, tg, tk, to, tt, tn, tr, tm, tc, tv, ug, ua, ae, um, uy, uz, vu, ve, vn, vg, vi, wf, eh, ye, zm, zw"
```

A nice to have would be to catch the error and print a message in the Javascript console.

**Comment by lbud** [comment]
Hey @pastcompute, thanks for your suggestion. mapbox-gl-geocoder fires an error message when it receives a status outside of the 200-399 range. We'd recommend implementing an error listener when you instantiate the geocoder [like the one in the example](https://github.com/mapbox/mapbox-gl-geocoder/blob/04f9678ed57656c67122b5fb57b475bfcd556911/example/index.js#L38-L40), which will do just what you're looking for.

**Comment by pastcompute** [comment]
No worries. It was missing in the API page which is what I was working from
