### ISSUE TITLE
sometimes Suggestions list isn't updated

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#48]
The Typeahead/suggestions are updated based on the results of the Geocoding response [here](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/index.js#L153) however the underlying suggestions library doesn't update the list in the [update method](https://github.com/tristen/suggestions/blob/gh-pages/src/suggestions.js#L109).

It updates `Suggestions.data` but this isn't feed back into the `Suggestions.list`, hence the results don't show up.

The [Suggestions test case](https://github.com/tristen/suggestions/blob/gh-pages/test/test.js#L136), dispatches some events after `Suggestions.update` which [actually update the Suggestions.list](https://github.com/tristen/suggestions/blob/gh-pages/src/suggestions.js#L66).

To fix this issue, the mapbox-gl-geocoder will need to either need to dispatch a keyup event or this needs to be addressed in Suggestions so that a call to `update` actually updates the `list`. I'm happy to put together a PR but I'm not sure which approach is best, to address in Suggestions or workaround it here?

**Comment by andrewharvey** [comment]
For me going to the example/index.html page and typing `C` then `r` then `o` doesn't populate any results (even though I can see the geocoding request go through), if I patch https://github.com/tristen/suggestions/blob/gh-pages/src/suggestions.js#L111 replacing `this.list.draw();` with `this.handleKeyUp();` which updates `this.list` then it works.

**Comment by weeman1337** [comment]
@andrewharvey I forked suggestions and put your fix in. Will test it for a while and report how it's working. If everything is fine I'll do some makeup and create pull requests.

**Comment by bbbford** [comment]
@weeman1337 How is has the testing been? I'm hopeful that this fix will make it into the next release. As I watch users on my site, I'm noticing that this behavior is causing them to abandon their session.

**Comment by andrewharvey** [comment]
> @andrewharvey I forked suggestions and put your fix in. Will test it for a while and report how it's working. If everything is fine I'll do some makeup and create pull requests.

Seems to fix the issue for me, are you going to create a pull request in tristen/suggestions?

**Comment by weeman1337** [comment]
So far it has been working fine for me.. Will create the pull request later.

**Comment by weeman1337** [comment]
Have to get the PR in suggestions through first
