### ISSUE TITLE
Selecting a suggestion does not work on mobile devices

### ISSUE THREAD

**Issue by jvence** [mapbox/mapbox-gl-geocoder#49]
I've added the geocoder to a mobile app but when I touch click on a item from the list, the list simply closes and the suggestion is never selected.

**Comment by jvence** [comment]
It doesn't even work when using the mouse in a browser.

**Comment by jvence** [comment]
Seems to be an issue with the framework I am using. Will close for now.

**Comment by jasoncoding** [comment]
@jvence I know it's been awhile but I'm facing a similar issue.  What was the issue with your framework?

**Comment by Andrew67** [comment]
@jasoncoding I can't speak for @jvence but I found that on a webapp I'm building which uses OnsenUI framework, it pulls in the FastClick library inside UIWebView (which if you do a homescreen webapp is what gets used), and the Geocoder doesn't play well with it, as I ran into this exact issue.

My solution was to add the `needsclick` CSS class to the results which excludes them from FastClick, by taking the default `render` function and tweaking it:
```js
new MapboxGeocoder({
    accessToken: mapboxgl.accessToken,
    mapboxgl: mapboxgl,
    render: function(item) {
        var placeName = item.place_name.split(',');
        return '<div class="mapboxgl-ctrl-geocoder--suggestion"><div class="mapboxgl-ctrl-geocoder--suggestion-title needsclick">'
            + placeName[0] + '</div><div class="mapboxgl-ctrl-geocoder--suggestion-address needsclick">'
            + placeName.splice(1, placeName.length).join(',') + '</div></div>';
     }
});
```
