### ISSUE TITLE
FlyTo speed geocoder result

### ISSUE THREAD

**Issue by martinrisseeuw** [mapbox/mapbox-gl-geocoder#51]
Just a quick question, is it possible to adjust the flyto speed of the geocoder since the FlyTo option is a boolean.

**Comment by tristen** [comment]
That was a bit of an oversight on my part. `flyTo` _should_ pass on the options available in https://www.mapbox.com/mapbox-gl-js/api/. 

---

As an interim solution you can set `flyTo: false`, listen for the result and write your own `map.flyTo`.

``` js
var geocoder = new mapboxgl.Geocoder({
  flyTo: false
});

geocoder.on('result', function(e) {
  var result = e.result;
  map.flyTo({
    // Pass result and custom animation
  });
});
```

**Comment by martinrisseeuw** [comment]
@tristen Thanks for the reply, seems to work now. Only problem that I have now is that with the standard geocoder it zooms further if the address is more specific. How should I add this to the custom animation? Do you have any suggestions for this.

**Comment by tristen** [comment]
Well this is travelling further down a rabbit hole but you can [infer from the source code](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/index.js#L82-L91) that it actually fits to bounds if the address is less specific and zooms to fixed zoom if it's more specific.

**Comment by martinrisseeuw** [comment]
@tristen Great, thanks for the help.

**Comment by tristen** [comment]
Oh! we should keep this open. I think we should totally pass `flyTo` options over!

**Comment by andrewharvey** [comment]
> Oh! we should keep this open. I think we should totally pass flyTo options over!

Agreed, for my use case it would nice to reset the pitch to 0 by simply passing it as an option to flyTo rather than rolling my own on result event handler.

**Comment by lbud** [comment]
This would be great — there's a lot moving in the Mapbox GL Camera API right now (https://github.com/mapbox/mapbox-gl-js/issues/2801); we should do this after that lands (as it is, mapbox-gl-geocoder uses different camera methods depending on the result).

**Comment by andrewharvey** [comment]
With #214 in mind, slated for v4.

I think we should try to decide if those flyTo options are also applied when fitting the map to a geocode bbox.

mapbox-gl-geocoder uses `fitBounds` when a bbox is found, and `fitBounds` also supports GL JS CameraOptions and AnimationOptions https://docs.mapbox.com/mapbox-gl-js/api/#map#fitbounds

**Comment by scottsfarley93** [comment]
👍 didn't realize these properties were available on the fitBounds method was well. I think we should pass any custom camera/animation options to the fitBounds calls as well.

**Comment by scottsfarley93** [comment]
This was done in a combination of #227 and #214. It will be available once version 4 is released.
