### ISSUE TITLE
Backspace does not work when also using mapbox-gl-draw

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-geocoder#57]
Example here - http://bl.ocks.org/danswick/c142d7afa2c9c511bfbea71b4273e61c. 

I have only been able to replicate this issue when using mapbox-gl-geocoder and mapbox-gl-draw at the same time. The first geocoding request works as expected, but if you clear the previous query and type a new one, backspace no longer works.

**Comment by tristen** [comment]
I suspect the issue needs to be resolved in mapbox-gl-draw: https://github.com/mapbox/mapbox-gl-draw/blob/0152ae608edab81b3d1cb0d28b14b6223ac3d337/src/events.js#L79

cc @mcwhittemore

**Comment by mcwhittemore** [comment]
@danswick - if you turn off the trash control, you should be ok. http://bl.ocks.org/mcwhittemore/2848175e2e727ed9ffab9335cbfe1d7c

That said, the delete key should only happen when the map is the target and not an input box. I'll open an issue in Draw for that.
