### ISSUE TITLE
Weird search results for United States, Canada and Russia

### ISSUE THREAD

**Issue by magnus-eriksson** [mapbox/mapbox-gl-geocoder#59]
When searching for United States, Canada or Russia, the map zooms out, showing the whole world instead of zooming in on those particular countries. It looks like it tries to do some positioning vertically, but it's not really accurate.

We have a map where we show stores all over the world, including in these three countries. so it's quite important that these, large, countries gets handled correctly.

**Comment by lbud** [comment]
Thanks for your report @magnus-eriksson. This is indeed unexpected behavior from a user's POV. What's happening is that mapbox-gl-geocoder zooms to the bounding box returned from the geocoding API, which includes the legal entirety of a country (so in the case of the USA the Aleutian Islands cross the International Date Line, or France includes the island of Reunion in the Indian Ocean, etc…)

The problem with bounding boxes including outlying islands is a complicated and political one and may be addressed in our geocoder eventually but isn't really on the roadmap right now. In the short run I'm addressing with #66.
