### ISSUE TITLE
.flyTo:false removes map-panning completely

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-geocoder#61]
Check out https://jsfiddle.net/dm5zw8gn/. While the code intends simply to remove the flyTo animation, it completely prevents the geocoder from moving the map to the desired spot

cc/ @tristen

**Comment by peterqliu** [comment]
Unsure if I'm reading this right, but [this if block](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/index.js#L81-L92) might need an `else`.

**Comment by tristen** [comment]
That's the intended behaviour. It allows an implementor to listen to geocoder events and animate in their own code or not.

**Comment by tristen** [comment]
What we should do is this though: https://github.com/mapbox/mapbox-gl-geocoder/issues/51
