### ISSUE TITLE
Inaccurate geocoordinates when selecting a 'region' result

### ISSUE THREAD

**Issue by bbbford** [mapbox/mapbox-gl-geocoder#62]
When selecting a geocoder result that is a 'region', the map zooms to the wrong spot.

It seems the result.center value is incorrect.

Example -
1. Use the example at https://www.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/
2. In the geocoder, type in 'Cork, Ireland' and select the result
3. Notice the map and the marker are now centered well west of Cork, Ireland.

![screen shot 2016-10-20 at 10 50 59 pm](https://cloud.githubusercontent.com/assets/5225875/19586098/c0909ed8-9717-11e6-9e4e-c921f88423f6.png)

**Comment by lbud** [comment]
Hey @bbbford, it looks like that particular `Cork` result is Cork County, Ireland. The second match is Cork City, Ireland, which looks like what you are expecting here.
Here are the bounding boxes and center results for those two (Cork (1) blue, Cork City (2) red)
![image](https://cloud.githubusercontent.com/assets/3170312/19948534/40b5c3ee-a10a-11e6-8a78-28953e1da2ff.png)
(You can see the full results for a query of "cork" at `https://api.mapbox.com/geocoding/v5/mapbox.places/cork.json?access_token=<access token>` )

It seems that the Cork County center is indeed correct.
![image](https://cloud.githubusercontent.com/assets/3170312/19948633/cf89d54c-a10a-11e6-831e-404c1de7f196.png)
