### ISSUE TITLE
debounce function closing

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [mapbox/mapbox-gl-geocoder#64]
Should the debounce call capture the timeout value at line 78?  I'm wondering if that line of code should read

```
 }.bind(this), 200));
```

instead of 

```
 }.bind(this)), 200);
```

Feel free to close this ticket.

**Comment by lbud** [comment]
It should, thanks for catching @wheredoesyourmindgo! Fixing in #65, to be included in the next release.
