### ISSUE TITLE
Use mapbox-sdk-js

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-geocoder#73]
Currently this module does its own URL construction and supports a limited set of params. Rely on mapbox-sdk-js instead.

**Comment by tristen** [comment]
There's currently no good way to [cancel requests](https://github.com/mapbox/mapbox-sdk-js/issues/89) in mapbox-sdk-js which the geocoder makes a ton of use from.

**Comment by tmcw** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-geocoder/pull/70
