### ISSUE TITLE
getResult gets the input

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-geocoder#77]
```
  /**
   * Return the input
   * @returns {Object} input
   */
  getResult: function() {
    return this._input;
  },
```

Does it return the result or the input? The docs and code say input, the method name says the result. Generally the result and input are on opposite sides. Which is the intent @tristen ?

**Comment by tristen** [comment]
Yikes. I think this should be the result of input if a result exists.

**Comment by tmcw** [comment]
So, it should return the result. If that's the case, I think we should remove this method entirely: we already have a `results` event that emits results. I'm already targeting a 2.0.0 release because the API surface will be reduced.

**Comment by tmcw** [comment]
Removed getResult in https://github.com/mapbox/mapbox-gl-geocoder/pull/70/commits/344303c3ae59a2dad00a45201386acf677a0ce0b

I think this ticket still needs more straightforwarding. As far as I can tell, [_input is actually selected](https://github.com/mapbox/mapbox-gl-geocoder/blob/344303c3ae59a2dad00a45201386acf677a0ce0b/lib/index.js#L115), which is quite confusing, given that it is named very similarly to `_inputEl` but has nothing to do with `_inputEl`. I'm planning on removing `_input` for now, and making sure that the other names of variables actually are what they are called.

**Comment by tmcw** [comment]
fixed in https://github.com/mapbox/mapbox-gl-geocoder/pull/70
