### ISSUE TITLE
flyTo=false disables all map movement, not just animation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-geocoder#78]
https://github.com/mapbox/mapbox-gl-geocoder/blob/344303c3ae59a2dad00a45201386acf677a0ce0b/lib/index.js#L94-L114

All map movement is within a `if (this.options.flyTo)` clause. I'm assuming that this is not the intent: flyTo is documented as disabling _animation_, but I can't imagine that implying that it disables all map movement, because that's essentially what the function of this control.

But it looks like this has [been the behavior of flyTo](https://github.com/mapbox/mapbox-gl-geocoder/commit/e4be4179bf406626e1d5ad22d591d358d0a45d19#diff-168726dbe96b3ce427e7fedce31bb0bcR69) since the beginning - can you confirm if "no movement" is the intent @tristen ? If so, we need to rename and redocument the option.

**Comment by tristen** [comment]
This is terrible. `flyTo` should just hand off options to the map object. Related:  https://github.com/mapbox/mapbox-gl-geocoder/issues/51
