### ISSUE TITLE
mapbox-gl-geocoder example is broken?

### ISSUE THREAD

**Issue by tborenst** [mapbox/mapbox-gl-geocoder#84]
https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/
Not sure if it's just me, but I have tried this on several devices and the above example is broken.
No Geocoding control shows up on the map.

In the console, I get the error messages:
`mapbox-gl-geocoder.js:1 Uncaught TypeError: mapboxgl.util.inherit is not a function(…)`
`(index):9 Uncaught TypeError: mapboxgl.Geocoder is not a constructor(…)`

Interestingly, I am experiencing similar problems with the `mapbox-gl-draw` example, but it worked a few days ago.

**Comment by tmcw** [comment]
-> #67 merged in https://github.com/mapbox/mapbox-gl-geocoder/pull/70 fixed in next release
