### ISSUE TITLE
options.accessToken always required? or bug in detecting global mapboxgl.accessToken

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#85]
According to `API.md` "options.accessToken [String] Required unless mapboxgl.accessToken is set globally (optional, default null)".

However if I set the `mapboxgl.accessToken` global and omit `options.accessToken` it errors with `mapbox-gl-geocoder.js:1 Uncaught Invariant Violation: accessToken required to instantiate Mapbox client` -> http://jsbin.com/tuxiwo/edit?html,output

I'm not sure if it's intended that `options.accessToken` is now mandatory and the docs need updating or if it's a bug where the global isn't being detected.

I'd much rather the scenario where I'm able to set the  `mapboxgl.accessToken` global once and not have to deal with setting it again in the geocoder, directions etc. controls, which I think is simpler for API users.

**Comment by tristen** [comment]
> I'm not sure if it's intended that `options.accessToken` is now mandatory and the docs need updating or if it's a bug where the global isn't being detected.

@andrewharvey Yep! that needs updating. The goal in [v2](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/CHANGELOG.md#v200) is to not rely on a `mapboxgl` global. So less convenient but more direct.
