### ISSUE TITLE
Mapbox example doesn't have a geocoder

### ISSUE THREAD

**Issue by drgrubman** [mapbox/mapbox-gl-geocoder#88]
The [example here](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/) does not show a geocoder. Also was curious on how to put that geocoder in a container. Things look a little different in v2.

**Comment by tmcw** [comment]
@mapsam looks like that example was updated to point at a v2.0.1 CDN version of Mapbox GL Geocoder, but that version isn't up on the CDN.

**Comment by mapsam** [comment]
Cripes. It is deployed but the recent 2.x fix now creates a `.min.js` instead of a regular `.js` file for releasing. I'll update the example doc to reflect this.

**Comment by mapsam** [comment]
Fix coming in https://github.com/mapbox/mapbox-gl-geocoder/issues/88#issuecomment-262375945

**Comment by mapsam** [comment]
@drgrubman non `.js` build is now living at the CDN and the example is up and running again. Thanks for reporting!
