### ISSUE TITLE
mapbox-gl-geocoder mobile styles

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/mapbox-gl-geocoder#89]
The geocoder plugin may appear quite big especially on mobile or when you have already other buttons on the map controls 

Today style:
![geocoder](https://cloud.githubusercontent.com/assets/10407788/20799080/1cd2f422-b7af-11e6-9a15-1a140bf6a43b.jpg)

I think it will be good to have at least an `collapsed` option to make the geocoder plugin small or big like in http://www.liedman.net/leaflet-control-geocoder/

`wanted style` 
![capture d ecran 2016-12-01 a 10 03 04](https://cloud.githubusercontent.com/assets/10407788/20799230/8ebbbb14-b7af-11e6-973d-1b35e421ca0a.png)

**Comment by tristen** [comment]
I'm inclined to require this from the implementor rather than building in an option to support this (see https://www.mapbox.com/imagery-requests/ as example)

**Comment by vincentsarago** [comment]
all good! 👌 
can we maybe update the documentation ?

**Comment by tristen** [comment]
Yeah ... I wonder how we should document this ...

**Comment by yuletide** [comment]
I'm having issues with the control working on mobile at all. Often it won't respond to touch events, and the autocomplete results are hard to see/interact with. Adding some responsive styling or docs for how to add them later would be very helpful.

**Comment by katydecorah** [comment]
Noting that we added a collapse option in the upcoming version 4, ref https://github.com/mapbox/mapbox-gl-geocoder/pull/222.

Leaving this issue until we cover mobile styling in version 4 as well.

**Comment by scottsfarley93** [comment]
We addressed these issues in #233 and #222. Mobile styles should be better handled once version 4 . is released.
