### ISSUE TITLE
include geocoder in div element

### ISSUE THREAD

**Issue by iskandarblue** [mapbox/mapbox-gl-geocoder#91]
The `.mapboxgl-ctrl-top-right` option allows one to specify the location/width of the geocoder on the screen, but is it possible to include the mapbox-gl geocoder in a `div` element, and if possible, how would one do that? 

The sample code below is taken from Mapbox `Add a geocoder` example. I would like include the geocoder in the `#header` element

```

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }


        #header {
          position: absolute;
          z-index: 1012022;
          top: 0px;
          width: 100%;
          line-height: 50px;
          height: 50px;
          background: rgba(12, 12, 12, 0.8);
          color: #eee;
        }

    </style>
</head>
<body>


<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.css' type='text/css' />
<div id='header'></div>
<div id='map'></div>


<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiaXNrYW5kYXJibHVlIiwiYSI6ImNpazE3MTJldjAzYzZ1Nm0wdXZnMGU2MGMifQ.i3E1_b9QXJS8xXuPy3OTcg';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-79.4512, 43.6568],
    zoom: 13
});

map.addControl(new MapboxGeocoder({
    accessToken: mapboxgl.accessToken
}));
</script>

</body>
</html>
```

**Comment by tristen** [comment]
Hey @iskandarblue It's possble! see https://github.com/mapbox/mapbox-gl-js/issues/3685#issuecomment-262394162. And here's an example: http://bl.ocks.org/tristen/a09627f01d3a3bc54139d52a5eb01386/

**Comment by TrulsLoug** [comment]
This example returs ERROR `TypeError: Cannot read property 'onAdd' of undefined` for me.

Here's my code snippet `
    var geocoder = new MapboxGeocoder({
    accessToken: mapboxgl.accessToken,
    localGeocoder: this.forwardGeocoder.bind(this), 
    zoom: 14,
    country: 'null',
});
  //this.map.addControl(geocoder);
  document.getElementById('geocoder').appendChild(this.geocoder.onAdd(map))`

**Comment by andrewharvey** [comment]
^ looks like you set geocoder not this.geocoder.

**Comment by TrulsLoug** [comment]
^ Thank you for the quick response, This fix the original issue but i had to comment out 
`this.map.addControl(geocoder);`
Doing so brought up a seperate issue. 

![image](https://user-images.githubusercontent.com/45484423/51246886-c3f0d680-198b-11e9-9012-b6b17e9c1d32.png) 

This happens when I'm searching for a item. Any clue why? Is it tied to `map.addControl`

**Comment by TrulsLoug** [comment]
Including `this.map.addControl(geocoder);` 
Brings up the issue of making the first searchbar non functioning and the second functioning 
![image](https://user-images.githubusercontent.com/45484423/51248005-11227780-198f-11e9-983e-691a35ace673.png)

**Comment by andrewharvey** [comment]
My guess is its something specific to your setup/framework since it's working in the example at https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-outside-the-map/

**Comment by girishts** [comment]
is it possible to achieve the same thing in mapbox.js  ?
we are still using mapbox js and not mapbox gl

I tried like this but it is not working.


geocontroler =L.mapbox.geocoderControl('mapbox.places', {
                autocomplete: true,
        });

 document.getElementById('geocoder').appendChild( geocoder.onAdd(map))

**Comment by kaitlynbrown** [comment]
What if I want to place the geocoder input on a page by itself *without* the map at all. Is there a way to do this?

**Comment by andrewharvey** [comment]
> What if I want to place the geocoder input on a page by itself without the map at all. Is there a way to do this?

@kaitlynbrown that's #270. I guess you could still have a map but just hide it from display, otherwise until someone does #270 you could use mapbox-sdk-js to build your own map-less search control. But be aware of the TOS https://www.mapbox.com/tos/#geocoding.

**Comment by kaitlynbrown** [comment]
My use case doesn't violate the tos - I just want to give users an opportunity to search for a location on a landing page, before being taken to the map. Adding a hidden map would probably incur extra charges from mapbox, so I'm just going to use [react-geocoder-autocomplete](https://github.com/emanueloliveira23/react-geocoder-autocomplete) for the time being

**Comment by andrewharvey** [comment]
> Adding a hidden map would probably incur extra charges from mapbox,

Not if you set an empty style.

> I'm just going to use react-geocoder-autocomplete for the time being

Yep, mapbox-gl-geocoder was originally written to be a control on the map, until #270 lands, your best option is to write your own autocomplete or use something like react-geocoder-autocomplete.
