### ISSUE TITLE
Options {container, proximity} no longer exists in v2

### ISSUE THREAD

**Issue by theentirety** [mapbox/mapbox-gl-geocoder#92]
In version 1.x there was a container that could be passed into the initialization options to attach the geocoder to a specific dom element. Similarly, there was a proximity that would allow for the results to be based on a particular lat/long, also gone. These appear to be removed and is a breaking change for our product. Any ideas on bringing these back or reasons for their removal?

**Comment by cityhubla** [comment]
@theentirety, 
proximity option is still there, it's written as `{proximity:{longitude:-118.2517,latitude:34.0545}`, just replace the numbers with yours, and you should be good. I'm also using V2 as well for some map work. Unsure about the `container` reasons, but the change mention is in the [CHANGELOG](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/CHANGELOG.md)

**Comment by adam-malowiecki** [comment]
Our product also uses the container feature and we are unable to upgrade Mapbox or Geocoder until this is fixed. We would also really appreciate some answer regarding if this is being fixed or why it has been removed.

**Comment by tristen** [comment]
Sorry for the delay responding to this! as @cityhubla mentioned, the proximity option is available (and for that matter [all the request options documented here](https://www.mapbox.com/api-documentation/#request-format)). 

As for attaching to a container, a direct option to specify a container was dropped in favour of aligning better with https://github.com/mapbox/mapbox-gl-js which doesn't have a built-in mechanism for specifying elements outside the map container. 

But it's still possible! `addTo` returns the control container so you can append it to any arbitrary DOM node. Here's an example of that: http://bl.ocks.org/tristen/a09627f01d3a3bc54139d52a5eb01386
