### ISSUE TITLE
Ignoring the 'zoom' option...

### ISSUE THREAD

**Issue by udoobu** [mapbox/mapbox-gl-geocoder#94]
Hi! I added a Geocoder control to my map but it's not using the zoom level that I specified. It seems to still be using the default zoom level of 16. Here's my code:

map.addControl(new MapboxGeocoder({
    accessToken: mapboxgl.accessToken,
    zoom: 6,
    placeholder: 'Search for locations...'
}));

**Comment by andrewharvey** [comment]
Keep in mind that the fixed zoom is only used when the [geocoder response](https://www.mapbox.com/api-documentation/#response-format) doesn't return a bbox. When it returns a bbox it will fit to the bounds instead.

Is this the issue you're facing.

I feel the documentation could be clearer in this regard.

**Comment by tristen** [comment]
Going to close this. Feel free to re-open if ^ is not what you are illustrating. For complete control you can set the [flyTo](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#mapboxgeocoder) option to false and do the flyto animation yourself by [listening to the results](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#on) event.

**Comment by ramesh-thati** [comment]
Hi Team,
How can i set the zoom level based on search result. for example
 country: zoomlevel 3 and state: zoomlevel:4

**Comment by sputn1k** [comment]
i want to know too?

**Comment by computersone** [comment]
Has anyone figured out how to search for anywhere and have it be at the same zoom level? It seems to drop to a bbox and there is no solution to keep the zoom the same. Any ideas?

**Comment by andrewharvey** [comment]
> Has anyone figured out how to search for anywhere and have it be at the same zoom level? It seems to drop to a bbox and there is no solution to keep the zoom the same. Any ideas?

You can try Tristen's suggestion from above:

> For complete control you can set the flyTo option to false and do the flyto animation yourself by listening to the results event.
