### ISSUE TITLE
Input doesn't show until map is clicked

### ISSUE THREAD

**Issue by Targun** [mapbox/mapbox-gl-geocoder#95]
Often the geocoder input doesn't visibly show until the map is clicked.  

Seems to be a chrome issue.

**Comment by tristen** [comment]
@Targun do you have an example of this happening I could take a look at? (as a [jsfiddle](https://jsfiddle.net/) os somesuch)?

**Comment by andrewharvey** [comment]
@Targun are you still seeing this?
