### ISSUE TITLE
API call made after 1 character typed even though no results shown until 2 characters typed

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#98]
[Inherited from Suggestions](https://github.com/tristen/suggestions/blob/gh-pages/API.md) by default two characters need to be typed into an input to trigger suggestions.

However the Geocoder still makes an API call to the Geocoding API after 1 character is typed. This wastes Geocoding API quota since it doesn't seem to be used anywhere.

Is this right? Would you accept a PR to skip the API call when the result won't be displayed?

**Comment by tristen** [comment]
https://github.com/mapbox/mapbox-gl-geocoder/pull/103
