### ISSUE TITLE
result event is invoked twice

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-geocoder#99]
http://jsbin.com/nalopux/edit?html,console,output

If I type something in the Geocoder then select an option, the `result` event is seemingly invoked twice with the same result.

**Comment by andrewharvey** [comment]
This is an upstream issue in suggestions

**Comment by brambow** [comment]
This is causing issues for me in a situation where I am trying to animate some layers that contain the resulting point of a geocode operation.  Since the result is invoked twice, my animation runs twice and looks weird.  Any ideas for a workaround appreciated.

**Comment by andrewharvey** [comment]
@brambow Do you mind testing the proposed solution at https://github.com/tristen/suggestions/issues/13

> If I disable the dispatch of the change event at https://github.com/tristen/suggestions/blob/gh-pages/src/suggestions.js#L151 the event is only triggered once and there doesn't seem to be any side affects.

I didn't notice any issue, if you don't either we can try to get a fix for this!

**Comment by brambow** [comment]
Yep.  That seems to fix it.

**Comment by ckc11** [comment]
This also fixed it for me as well.

**Comment by andrewharvey** [comment]
Just noting that removing this code does fix it for modern browsers but breaks it for IE11. https://github.com/tristen/suggestions/issues/13#issuecomment-313595481

**Comment by jwhazel** [comment]
Throwing in my request for a fix as well (preferably one that satisfies IE11). My current solution is to set up global to store the `latlng` and check to see if the new event is different than the last. Clearly not the most elegant solution.

```lastGeocode = "";
geocoder.on('result', function (e) {
	if(e.result.center.toString() !== lastGeocode){
		drawCustomMarker(e.result.center, e.result.place_name);
	}

	lastGeocode = e.result.center.toString();
});```

**Comment by pathmapper** [comment]
Using GL JS `v0.48.0` and Geocoder  `v2.3.0`, it looks like the behavior changed a bit compared to https://github.com/mapbox/mapbox-gl-geocoder/issues/99#issue-207780402:

The second `result` event is now fired after a click on the map (Chrome on Linux): 
https://jsbin.com/dapurelime/edit?html,console,output

**Comment by andrewharvey** [comment]
> The second result event is now fired after a click on the map (Chrome on Linux):

That's interesting, I'm also running Chrome on Linux and can't replicate that, in fact I'm only ever seeing the result event emitted once. :thinking:

**Comment by pathmapper** [comment]
@andrewharvey sometimes I also see only one result event.

It seems like it depends on
- what you are searching for
- which option is selected (if there are more than one)
- if there were geocoder searches before without reloading the page

With the following steps I get always a second result event after a click with the left mouse button (just noticed that the click must not be necessarily on the map): 
1. Type `Miami` in the Geocoder of the jsbin I've posted above.
2. Just hit `enter` on your keybord.
3. Click on the map with the left mouse button.

**Comment by andrewharvey** [comment]
@pathmapper Right, that's because hitting enter selects the result, but doesn't blur the input, only when you click the map does the input blur and it triggers result again.

I believe that points back to https://github.com/tristen/suggestions/issues/13 where the issue was ensuring result is triggered in all interactions (keyboard, mouse) across all supported browsers (IE11 was the issue), it was easy to fix for modern browsers, but I couldn't find a way to fix it such that it didn't break IE11.

**Comment by andrewharvey** [comment]
#218 implemented a workaround the underlying bug in the upstream suggestions library. So I'll go ahead and close this as the bug shouldn't be noticeable to end users anymore. This is slated for v4 release.
